"""StrategyRegistry — canonical catalogue of every orchestration strategy.
Every pattern from the architecture docs must be registered here with its state.
"""
from __future__ import annotations

import enum
from collections.abc import Mapping
from dataclasses import dataclass, field
from functools import lru_cache
from typing import Any

from app.rag.contracts import (
    RAG_RUNTIME_CAPABILITIES,
    RAGRuntimeAdapter,
    RAGStrategy,
    is_rag_runtime_adapter,
)


class StrategyState(str, enum.Enum):  # noqa: UP042
    IMPLEMENTED = "implemented"
    PARTIAL = "partial"
    PLANNED = "planned"
    DISABLED = "disabled"


class StrategyCategory(str, enum.Enum):  # noqa: UP042
    AGENT = "agent_patterns"
    RAG = "rag_patterns"
    SAFETY = "safety_patterns"
    MEMORY = "memory_patterns"
    OPTIMISATION = "optimisation_patterns"


@dataclass
class StrategyCapability:
    strategy_id: str
    category: StrategyCategory
    state: StrategyState
    adapter_path: str = ""
    description: str = ""
    required_deps: list[str] = field(default_factory=list)
    optional_deps: list[str] = field(default_factory=list)
    cost_class: str = "medium"
    latency_class: str = "interactive"
    risk_class: str = "low"
    compatible_goal_properties: dict[str, Any] = field(default_factory=dict)


class StrategyRegistry:
    def __init__(self, entries: list[StrategyCapability]) -> None:
        self._by_id: dict[str, StrategyCapability] = {e.strategy_id: e for e in entries}

    def get(self, strategy_id: str) -> StrategyCapability | None:
        return self._by_id.get(strategy_id)

    def list_all(self) -> list[StrategyCapability]:
        return list(self._by_id.values())

    def list_by_category(self, category: StrategyCategory) -> list[StrategyCapability]:
        return [e for e in self._by_id.values() if e.category == category]

    def filter(
        self,
        *,
        state: StrategyState | None = None,
        category: StrategyCategory | None = None,
        cost_class: str | None = None,
        latency_class: str | None = None,
    ) -> list[StrategyCapability]:
        results = list(self._by_id.values())
        if state is not None:
            results = [r for r in results if r.state == state]
        if category is not None:
            results = [r for r in results if r.category == category]
        if cost_class is not None:
            results = [r for r in results if r.cost_class == cost_class]
        if latency_class is not None:
            results = [r for r in results if r.latency_class == latency_class]
        return results

    def is_available(
        self, strategy_id: str, *, available_deps: set[str] | None = None
    ) -> bool:
        cap = self.get(strategy_id)
        if cap is None:
            return False
        if cap.category is StrategyCategory.RAG and cap.state is not StrategyState.IMPLEMENTED:
            return False
        if cap.state in (StrategyState.PLANNED, StrategyState.DISABLED):
            return False
        return available_deps is None or not set(cap.required_deps) - available_deps


def build_default_registry(
    *,
    rag_runtime_capabilities: Mapping[RAGStrategy, type[RAGRuntimeAdapter]] | None = None,
) -> StrategyRegistry:
    A = StrategyCategory.AGENT  # noqa: N806
    R = StrategyCategory.RAG  # noqa: N806
    S = StrategyCategory.SAFETY  # noqa: N806
    M = StrategyCategory.MEMORY  # noqa: N806
    O = StrategyCategory.OPTIMISATION  # noqa: E741, N806
    IMPL = StrategyState.IMPLEMENTED  # noqa: N806
    PART = StrategyState.PARTIAL  # noqa: N806
    PLAN = StrategyState.PLANNED  # noqa: N806

    runtime_capabilities = (
        RAG_RUNTIME_CAPABILITIES
        if rag_runtime_capabilities is None
        else rag_runtime_capabilities
    )
    entries: list[StrategyCapability] = [
        # ── Agent Patterns (26 from doc-4) ──────────────────────────────────
        StrategyCapability(
            "react",
            A,
            IMPL,
            "app.agent.graph:AgentGraph",
            "ReAct loop",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "plan_execute",
            A,
            IMPL,
            "app.agent.graph:AgentGraph",
            "Plan then execute",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "chain_of_thought",
            A,
            PART,
            "app.agent.graph:AgentGraph",
            "CoT reasoning",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "zero_shot_cot", A, PART, "", "Zero-shot CoT", [], [], "low", "interactive", "low"
        ),
        StrategyCapability(
            "few_shot_cot", A, PLAN, "", "Few-shot CoT", [], [], "medium", "interactive", "low"
        ),
        StrategyCapability(
            "reflection",
            A,
            IMPL,
            "app.agent.graph:AgentGraph",
            "Post-exec reflection",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "reflexion",
            A,
            IMPL,
            "",
            "Persistent failure lessons",
            [],
            [],
            "medium",
            "batch",
            "low",
        ),
        StrategyCapability(
            "self_refine",
            A,
            IMPL,
            "",
            "Iterative self-refinement",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "self_consistency",
            A,
            IMPL,
            "",
            "Multiple paths + majority vote",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        StrategyCapability(
            "tree_of_thoughts",
            A,
            IMPL,
            "",
            "Tree search over reasoning",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        StrategyCapability(
            "graph_of_thoughts",
            A,
            PLAN,
            "",
            "Graph-structured thought",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        StrategyCapability(
            "least_to_most",
            A,
            PLAN,
            "",
            "Decompose least to most complex",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "rewoo",
            A,
            PLAN,
            "",
            "Reasoning without observation",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "program_of_thought",
            A,
            PLAN,
            "",
            "Programs to solve tasks",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "codeact",
            A,
            PLAN,
            "",
            "Code execution as action",
            ["code_interpreter"],
            [],
            "medium",
            "interactive",
            "medium",
        ),
        StrategyCapability(
            "goal_tree",
            A,
            IMPL,
            "app.agent.goal_tree:GoalTree",
            "Parallel sub-goals",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        StrategyCapability(
            "supervisor",
            A,
            IMPL,
            "app.agent.supervisor:Supervisor",
            "Supervisor orchestration",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        StrategyCapability(
            "debate",
            A,
            IMPL,
            "app.agent.debate:DebateCoordinator",
            "Multi-agent debate",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        StrategyCapability(
            "mixture_of_agents",
            A,
            PLAN,
            "",
            "Ensemble of agents",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        StrategyCapability(
            "consensus",
            A,
            IMPL,
            "app.agent.consensus:ConsensusVerifier",
            "Consensus verification",
            [],
            [],
            "high",
            "batch",
            "medium",
        ),
        StrategyCapability(
            "peer_review", A, IMPL, "", "Peer agent review", [], [], "high", "batch", "low"
        ),
        StrategyCapability(
            "camel", A, PLAN, "", "Communicative agents", [], [], "high", "batch", "low"
        ),
        StrategyCapability(
            "babyagi",
            A,
            PLAN,
            "",
            "Task creation and prioritization",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        StrategyCapability(
            "autogpt",
            A,
            PLAN,
            "",
            "Autonomous long-horizon",
            [],
            [],
            "high",
            "batch",
            "medium",
        ),
        StrategyCapability(
            "lats", A, PLAN, "", "LLM Monte Carlo tree search", [], [], "high", "batch", "low"
        ),
        StrategyCapability(
            "llm_compiler",
            A,
            PLAN,
            "",
            "Parallel task compilation",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        # Additional from doc-1
        StrategyCapability(
            "structured_planning",
            A,
            IMPL,
            "app.agent.structured_plan",
            "Structured plan with depends_on",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "persistence_strategy",
            A,
            IMPL,
            "app.agent.persistence",
            "Smart retry with strategy rotation",
            [],
            [],
            "low",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "loop_engineering",
            A,
            IMPL,
            "app.agent.graph:AgentGraph",
            "loop_until + wave execution",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "loop_until",
            A,
            IMPL,
            "app.agent.graph:AgentGraph",
            "Loop step until condition",
            [],
            [],
            "low",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "wave_execution",
            A,
            IMPL,
            "app.agent.graph:AgentGraph",
            "Parallel wave execution",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "workflow_dag",
            A,
            IMPL,
            "app.agent.workflow_planner:WorkflowPlanner",
            "Static DAG workflow",
            [],
            [],
            "medium",
            "batch",
            "low",
        ),
        StrategyCapability(
            "skill_selector",
            A,
            IMPL,
            "app.agent.skill_selector",
            "Dynamic skill selection",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "intent_router",
            A,
            IMPL,
            "app.agent.router",
            "Auto-route to best agent",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "meta_agent_planner",
            A,
            PART,
            "app.intelligence.meta_agent",
            "NL → agent config",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        StrategyCapability(
            "scratchpad",
            A,
            IMPL,
            "app.agent.graph:AgentGraph",
            "CoT scratchpad",
            [],
            [],
            "low",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "budget_control",
            O,
            IMPL,
            "app.governance.cost:CostController",
            "Cost circuit breaker",
            [],
            [],
            "low",
            "realtime",
            "medium",
        ),
        StrategyCapability(
            "circuit_breaker",
            S,
            IMPL,
            "app.reliability.circuit_breaker:CircuitBreaker",
            "CLOSED→OPEN→HALF_OPEN",
            [],
            [],
            "low",
            "realtime",
            "medium",
        ),
        StrategyCapability(
            "grounding_checker",
            S,
            IMPL,
            "app.agent.grounding:GroundingChecker",
            "Hallucination detection",
            [],
            [],
            "low",
            "interactive",
            "medium",
        ),
        StrategyCapability(
            "constitutional_ai",
            S,
            PLAN,
            "",
            "Constitutional AI critique",
            [],
            [],
            "medium",
            "batch",
            "medium",
        ),
        StrategyCapability(
            "voyager", A, PLAN, "", "Skill-learning agent", [], [], "high", "batch", "low"
        ),
        StrategyCapability(
            "generative_agents",
            A,
            PLAN,
            "",
            "Memory-driven simulation",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        # ── RAG Patterns (17 from doc-4 + raft) ──────────────────────────────
        StrategyCapability(
            RAGStrategy.NAIVE.value,
            R,
            PART,
            "app.rag.store:KnowledgeStore",
            "Simple vector retrieval",
            ["knowledge_store"],
            ["embedder"],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.HYBRID.value,
            R,
            PART,
            "app.rag.store:KnowledgeStore",
            "Vector + trigram hybrid",
            ["knowledge_store"],
            ["embedder"],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.HYDE.value,
            R,
            PART,
            "app.rag_platform.retriever:RAGRetriever",
            "Hypothetical doc embeddings",
            ["knowledge_store", "embedder"],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.MULTI_HOP.value,
            R,
            PART,
            "app.rag_platform.retriever:RAGRetriever",
            "Multi-hop retrieval",
            ["knowledge_store", "embedder"],
            ["kg_store"],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.GRAPH.value,
            R,
            PART,
            "app.rag_platform.retriever:RAGRetriever",
            "KG augmented retrieval",
            ["kg_store"],
            ["knowledge_store"],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.CORRECTIVE.value,
            R,
            PART,
            "app.rag.agentic.patterns.corrective:CorrectiveRAGPattern",
            "Corrective retrieval",
            ["knowledge_store"],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.ADAPTIVE.value,
            R,
            PART,
            "app.rag.agentic.patterns.adaptive:AdaptiveRAGPattern",
            "Adaptive strategy per query",
            ["knowledge_store"],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.MODULAR.value,
            R,
            PLAN,
            "",
            "Pluggable RAG modules",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.SPECULATIVE.value,
            R,
            PART,
            "app.rag.agentic.patterns.speculative:SpeculativeRAGPattern",
            "Speculative retrieval",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.AGENTIC.value,
            R,
            PART,
            "app.rag_platform.retriever:RAGRetriever",
            "Agent-owned retrieval",
            ["knowledge_store"],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.WEB_AUGMENTED.value,
            R,
            PART,
            "app.tools.web_search:WebSearchTool",
            "Web search RAG",
            ["web_search"],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.FUSION.value,
            R,
            PART,
            "app.rag.agentic.patterns.fusion:FusionRAGPattern",
            "Multi-query RRF fusion",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.SELF_RAG.value,
            R,
            PART,
            "app.rag.agentic.patterns.self_rag:SelfRAGPattern",
            "Self-reflective retrieval",
            [],
            [],
            "high",
            "interactive",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.FLARE.value,
            R,
            PART,
            "app.rag.agentic.patterns.flare:FLAREPattern",
            "Forward-looking active retrieval",
            [],
            [],
            "high",
            "interactive",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.RAPTOR.value,
            R,
            PART,
            "app.rag.agentic.patterns.raptor:RAPTORPattern",
            "Recursive abstractive processing",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.AGENTIC_CHUNKING.value,
            R,
            PART,
            "app.rag.agentic.patterns.agentic_chunking:AgenticChunkingPattern",
            "LLM-driven chunking",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.COLBERT.value,
            R,
            PART,
            "app.rag.agentic.patterns.colbert:ColBERTPattern",
            "ColBERT late interaction",
            [],
            [],
            "medium",
            "interactive",
            "low",
        ),
        StrategyCapability(
            RAGStrategy.RAFT.value,
            R,
            PLAN,
            "",
            "RAG fine-tuning pattern",
            [],
            [],
            "high",
            "batch",
            "low",
        ),
        # ── Safety Patterns (10 from doc-4 + extras) ────────────────────────
        StrategyCapability(
            "guardrails",
            S,
            IMPL,
            "app.guardrails_v2.engine:guardrails_engine",
            "Input/output scanning",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "hitl",
            S,
            IMPL,
            "app.governance.hitl:HITLGateway",
            "Human approval gate",
            [],
            [],
            "low",
            "interactive",
            "high",
        ),
        StrategyCapability(
            "consensus_verification",
            S,
            IMPL,
            "app.agent.consensus:ConsensusVerifier",
            "Multi-agent consensus",
            [],
            [],
            "high",
            "batch",
            "medium",
        ),
        StrategyCapability(
            "exfiltration_guard",
            S,
            IMPL,
            "app.agent.exfil_guard",
            "Prevent data exfil",
            [],
            [],
            "low",
            "realtime",
            "high",
        ),
        StrategyCapability(
            "permission_matrix",
            S,
            IMPL,
            "app.governance.permissions:PermissionMatrix",
            "RBAC enforcement",
            [],
            [],
            "low",
            "realtime",
            "high",
        ),
        StrategyCapability(
            "policy_compiler",
            S,
            PLAN,
            "app.policy_runtime.compiler",
            "Compile policy constraints",
            [],
            [],
            "low",
            "realtime",
            "high",
        ),
        StrategyCapability(
            "sandbox",
            S,
            PLAN,
            "app.sandbox_runtime.executor",
            "Isolated execution",
            [],
            [],
            "medium",
            "interactive",
            "high",
        ),
        StrategyCapability(
            "plan_verification",
            S,
            PLAN,
            "app.plan_runtime.plan_verifier",
            "Verify plan before exec",
            [],
            [],
            "low",
            "realtime",
            "high",
        ),
        StrategyCapability(
            "data_classification",
            S,
            PLAN,
            "app.data_classification.classifier",
            "Classify data before prompt",
            [],
            [],
            "low",
            "realtime",
            "high",
        ),
        StrategyCapability(
            "provenance_verification",
            S,
            PLAN,
            "app.provenance.ledger",
            "Claim-level provenance",
            [],
            [],
            "medium",
            "batch",
            "medium",
        ),
        StrategyCapability(
            "rollback",
            S,
            IMPL,
            "app.reliability.rollback:RollbackEngine",
            "LIFO rollback",
            [],
            [],
            "low",
            "realtime",
            "high",
        ),
        # ── Memory Patterns (8 from doc-4) ───────────────────────────────────
        StrategyCapability(
            "working_memory",
            M,
            IMPL,
            "app.agent.state:AgentState",
            "In-context working memory",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "session_memory",
            M,
            IMPL,
            "app.memory.execution:ExecutionMemory",
            "Session execution memory",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "execution_memory",
            M,
            IMPL,
            "app.memory.execution:ExecutionMemory",
            "Cross-run plan memory",
            [],
            [],
            "low",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "long_term_memory",
            M,
            IMPL,
            "app.memory.long_term:LongTermMemoryStore",
            "Cross-session learnings",
            [],
            [],
            "low",
            "interactive",
            "low",
        ),
        StrategyCapability(
            "semantic_memory",
            M,
            IMPL,
            "app.rag.semantic_cache:SemanticCache",
            "Semantic cache",
            ["embedder"],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "prospective_memory",
            M,
            PLAN,
            "",
            "Future task scheduling",
            [],
            [],
            "low",
            "batch",
            "low",
        ),
        StrategyCapability(
            "reflexion_memory",
            M,
            PART,
            "app.state_runtime.reflexion_store",
            "Failure lesson store",
            [],
            [],
            "low",
            "batch",
            "low",
        ),
        StrategyCapability(
            "knowledge_graph_memory",
            M,
            PART,
            "app.knowledge_graph.store:KnowledgeGraphStore",
             "KG memory",
             [],
             [],
             "medium",
             "interactive",
             "low",
         ),
        StrategyCapability(
             "episodic_memory",
             M,
             IMPL,
             "app.memory.episodic:EpisodicMemoryStore",
             "Past experience recall — stores goal outcomes for contextual planning",
             [],
             [],
             "medium",
             "interactive",
             "low",
         ),
        StrategyCapability(
             "procedural_memory",
             M,
             IMPL,
             "app.memory.procedural:ProceduralMemoryStore",
             "Learned tool-use patterns — suggests proven tool sequences for goal types",
             [],
             [],
             "medium",
             "interactive",
             "low",
         ),
         # ── Optimisation Patterns (11 from doc-4) ────────────────────────────
        StrategyCapability(
            "model_routing",
            O,
            IMPL,
            "app.ai_router.router:AIRouter",
            "Dynamic model selection",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "embedding_routing",
            O,
            PART,
            "",
            "Dynamic embedding selection",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "token_optimisation",
            O,
            PART,
            "app.agent.prompt_compressor",
            "Prompt compression",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "cost_optimisation",
            O,
            PART,
            "app.intelligence.cost_optimizer",
            "Cost-aware selection",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "latency_optimisation",
            O,
            PLAN,
            "",
            "Latency-aware routing",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "semantic_cache",
            O,
            IMPL,
            "app.rag.semantic_cache:SemanticCache",
            "Semantic LLM caching",
            ["embedder"],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "llm_response_cache",
            O,
            IMPL,
            "app.rag.llm_response_cache",
            "Deterministic LLM cache",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "prompt_ab_testing",
            O,
            PLAN,
            "",
            "Prompt A/B testing",
            [],
            [],
            "low",
            "batch",
            "low",
        ),
        StrategyCapability(
            "model_ab_testing",
            O,
            PLAN,
            "",
            "Model routing A/B testing",
            [],
            [],
            "low",
            "batch",
            "low",
        ),
        StrategyCapability(
            "prompt_compression",
            O,
            PART,
            "app.agent.prompt_compressor",
            "Compress prompts",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
        StrategyCapability(
            "context_budgeting",
            O,
            PLAN,
            "app.context.context_budget",
            "Context token budgets",
            [],
            [],
            "low",
            "realtime",
            "low",
        ),
    ]
    for capability in entries:
        if capability.category is not R:
            continue
        strategy = RAGStrategy(capability.strategy_id)
        adapter = runtime_capabilities.get(strategy)
        if adapter is not None and is_rag_runtime_adapter(strategy, adapter):
            capability.state = IMPL
            capability.adapter_path = f"{adapter.__module__}:{adapter.__name__}"
        elif capability.state not in (PLAN, StrategyState.DISABLED):
            capability.state = PART

    return StrategyRegistry(entries)


@lru_cache(maxsize=1)
def get_strategy_registry() -> StrategyRegistry:
    """Return the default strategy registry, built once at startup."""
    return build_default_registry()
