"""A minimal in-process SMTP server for tests (``aiosmtpd`` is not in the venv).

Plain-text SMTP on 127.0.0.1 with an ephemeral port: EHLO, AUTH PLAIN (one
fixed credential pair, generated by the test), MAIL / RCPT / DATA, NOOP, RSET,
QUIT. Received messages are kept on ``server.messages``. No TLS.
"""

from __future__ import annotations

import asyncio
import base64
from dataclasses import dataclass, field


@dataclass
class Received:
    mail_from: str
    rcpt_to: list[str]
    data: str
    authenticated_as: str | None


@dataclass
class FakeSMTPServer:
    username: str | None = None
    secret: str | None = None
    messages: list[Received] = field(default_factory=list)
    auth_attempts: int = 0
    port: int = 0
    _server: asyncio.AbstractServer | None = None

    async def start(self) -> FakeSMTPServer:
        self._server = await asyncio.start_server(self._handle, "127.0.0.1", 0)
        self.port = int(self._server.sockets[0].getsockname()[1])
        return self

    async def stop(self) -> None:
        if self._server is not None:
            self._server.close()
            await self._server.wait_closed()

    async def __aenter__(self) -> FakeSMTPServer:
        return await self.start()

    async def __aexit__(self, *_exc: object) -> None:
        await self.stop()

    async def _handle(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
        async def reply(line: str) -> None:
            writer.write((line + "\r\n").encode())
            await writer.drain()

        user: str | None = None
        mail_from = ""
        rcpts: list[str] = []
        await reply("220 fake.test ESMTP ready")
        try:
            while True:
                raw = await reader.readline()
                if not raw:
                    return
                line = raw.decode().rstrip("\r\n")
                verb = line.split(" ", 1)[0].upper()
                arg = line[len(verb) :].strip()
                if verb in ("EHLO", "HELO"):
                    extensions = ["250-fake.test", "250-8BITMIME"]
                    if self.username is not None:
                        extensions.append("250-AUTH PLAIN")
                    extensions.append("250 OK")
                    writer.write(("\r\n".join(extensions) + "\r\n").encode())
                    await writer.drain()
                elif verb == "AUTH":
                    self.auth_attempts += 1
                    parts = arg.split(" ", 1)
                    if parts[0].upper() != "PLAIN":
                        await reply("504 unsupported mechanism")
                        continue
                    token = parts[1] if len(parts) > 1 else ""
                    if not token:
                        await reply("334 ")
                        token = (await reader.readline()).decode().strip()
                    try:
                        _, name, pw = base64.b64decode(token).decode().split("\0")
                    except Exception:
                        await reply("501 malformed")
                        continue
                    if name == self.username and pw == self.secret:
                        user = name
                        await reply("235 authenticated")
                    else:
                        await reply("535 authentication failed")
                elif verb == "MAIL":
                    if self.username is not None and user is None:
                        await reply("530 authentication required")
                        continue
                    mail_from = arg.split(":", 1)[1].strip().strip("<>").split(">")[0]
                    rcpts = []
                    await reply("250 OK")
                elif verb == "RCPT":
                    rcpts.append(arg.split(":", 1)[1].strip().strip("<>").split(">")[0])
                    await reply("250 OK")
                elif verb == "DATA":
                    await reply("354 end with .")
                    lines: list[str] = []
                    while True:
                        data_line = (await reader.readline()).decode()
                        if data_line.rstrip("\r\n") == ".":
                            break
                        lines.append(data_line)
                    self.messages.append(Received(mail_from, list(rcpts), "".join(lines), user))
                    await reply("250 queued")
                elif verb in ("NOOP", "RSET"):
                    await reply("250 OK")
                elif verb == "QUIT":
                    await reply("221 bye")
                    return
                else:
                    await reply("502 not implemented")
        finally:
            writer.close()
