apiVersion: v1
kind: Service
metadata:
  name: agentverse-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: agentverse-backend
    {{- include "agentverse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: agentverse-backend
  ports:
    - port: 80
      targetPort: 8000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: agentverse-frontend
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: agentverse-frontend
  ports:
    - port: 80
      targetPort: 80
      name: http
