"""Pre-built connector catalog — 32 popular services ready to connect.

Each ConnectorSpec is a template: the user supplies their credentials and
the registry instantiates an MCPServerConfig from the spec + their auth config.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class AuthFieldSpec:
    key: str
    label: str
    placeholder: str
    field_type: str  # "text" | "password" | "url" | "email"
    required: bool = True
    hint: str = ""


# Per-connector auth field overrides (richer hints than generic)
_CONNECTOR_AUTH_FIELDS: dict[str, list[AuthFieldSpec]] = {
    "jira": [
        AuthFieldSpec("url", "Jira URL", "https://mycompany.atlassian.net", "url", hint="Your Atlassian Cloud or Server instance URL"),
        AuthFieldSpec("username", "Email", "you@company.com", "email", hint="Your Atlassian account email address"),
        AuthFieldSpec("password", "API Token", "ATATT3xFfGF0...", "password", hint="Create at id.atlassian.com/manage-profile/security/api-tokens"),
    ],
    "github": [
        AuthFieldSpec("token", "Personal Access Token", "ghp_xxxxxxxxxxxx", "password", hint="Create at github.com/settings/tokens — needs repo scope"),
        AuthFieldSpec("url", "GitHub URL", "https://api.github.com", "url", required=False, hint="Leave blank for github.com; override for GitHub Enterprise"),
    ],
    "confluence": [
        AuthFieldSpec("url", "Confluence URL", "https://mycompany.atlassian.net", "url"),
        AuthFieldSpec("username", "Email", "you@company.com", "email"),
        AuthFieldSpec("password", "API Token", "ATATT3x...", "password"),
    ],
    "slack": [
        AuthFieldSpec("token", "Bot Token", "xoxb-xxxxxxxxxxxx", "password", hint="Create a Slack App and use the Bot Token from OAuth & Permissions"),
    ],
    "linear": [
        AuthFieldSpec("api_key", "API Key", "lin_api_xxxxxxxx", "password", hint="Create at linear.app/settings/api"),
    ],
    "gitlab": [
        AuthFieldSpec("token", "Personal Access Token", "glpat-xxxx", "password"),
        AuthFieldSpec("url", "GitLab URL", "https://gitlab.com/api/v4", "url", required=False),
    ],
    "hubspot": [
        AuthFieldSpec("api_key", "Access Token", "pat-na1-xxxxxxxx", "password", hint="Use a Private App token from your HubSpot account"),
    ],
    "stripe": [
        AuthFieldSpec("token", "Secret Key", "sk_live_xxxxxxxx", "password", hint="Find in Stripe Dashboard > Developers > API keys"),
    ],
    "datadog": [
        AuthFieldSpec("DD-API-KEY", "API Key", "your-api-key", "password"),
        AuthFieldSpec("DD-APPLICATION-KEY", "Application Key", "your-app-key", "password"),
    ],
    "sentry": [
        AuthFieldSpec("token", "Auth Token", "sntrys_xxx", "password"),
        AuthFieldSpec("SENTRY_ORG", "Organization Slug", "my-org", "text"),
    ],
    "aws": [
        AuthFieldSpec("AWS_ACCESS_KEY_ID", "Access Key ID", "AKIAIOSFODNN7EXAMPLE", "text"),
        AuthFieldSpec("AWS_SECRET_ACCESS_KEY", "Secret Access Key", "wJalrXUtnFEMI...", "password"),
        AuthFieldSpec("AWS_DEFAULT_REGION", "Region", "us-east-1", "text", required=False),
    ],
    "postgresql": [
        AuthFieldSpec("url", "Connection URL", "postgresql://user:pass@localhost:5432/mydb", "url"),
    ],
}

# Generic defaults by auth_type
_DEFAULT_AUTH_FIELDS: dict[str, list[AuthFieldSpec]] = {
    "bearer": [AuthFieldSpec("token", "Access Token", "your-token", "password")],
    "api_key": [AuthFieldSpec("api_key", "API Key", "your-api-key", "password")],
    "basic": [
        AuthFieldSpec("username", "Username", "your-username", "text"),
        AuthFieldSpec("password", "Password", "your-password", "password"),
    ],
    "connection_string": [AuthFieldSpec("url", "Connection URL", "service://host:port/db", "url")],
    "oauth_ac": [
        AuthFieldSpec("client_id", "Client ID", "your-client-id", "text"),
        AuthFieldSpec("client_secret", "Client Secret", "your-client-secret", "password"),
    ],
}


@dataclass(frozen=True)
class ConnectorSpec:
    name: str
    description: str
    auth_type: str
    default_url: str
    icon: str = ""
    category: str = "other"
    builtin_server_id: str = ""
    display_name: str = ""

    @property
    def auth_fields(self) -> list[AuthFieldSpec]:
        if self.name in _CONNECTOR_AUTH_FIELDS:
            return _CONNECTOR_AUTH_FIELDS[self.name]
        return _DEFAULT_AUTH_FIELDS.get(self.auth_type, [])


CONNECTOR_CATALOG: list[ConnectorSpec] = [
    # ── Original 9 ───────────────────────────────────────────────────────────
    ConnectorSpec(
        name="github",
        description="GitHub — code repositories, PRs, issues, Actions",
        auth_type="bearer",
        default_url="https://api.github.com",
        icon="github",
        category="devtools",
        builtin_server_id="builtin-github",
        display_name="GitHub",
    ),
    ConnectorSpec(
        name="jira",
        description="JIRA — project management, issue tracking, sprints",
        auth_type="basic",
        default_url="https://your-domain.atlassian.net",
        icon="jira",
        category="project_management",
        builtin_server_id="builtin-jira",
        display_name="Jira",
    ),
    ConnectorSpec(
        name="slack",
        description="Slack — messaging, channels, workflows, notifications",
        auth_type="bearer",
        default_url="https://slack.com/api",
        icon="slack",
        category="communication",
        builtin_server_id="builtin-slack",
        display_name="Slack",
    ),
    ConnectorSpec(
        name="salesforce",
        description="Salesforce — CRM, leads, opportunities, accounts",
        auth_type="oauth_ac",
        default_url="https://login.salesforce.com",
        icon="salesforce",
        category="crm",
        display_name="Salesforce",
    ),
    ConnectorSpec(
        name="linear",
        description="Linear — engineering issue tracking, cycles, roadmaps",
        auth_type="api_key",
        default_url="https://api.linear.app",
        icon="linear",
        category="project_management",
        builtin_server_id="builtin-linear",
        display_name="Linear",
    ),
    ConnectorSpec(
        name="notion",
        description="Notion — wiki, docs, databases, tasks",
        auth_type="bearer",
        default_url="https://api.notion.com",
        icon="notion",
    ),
    ConnectorSpec(
        name="sentry",
        description="Sentry — error tracking, performance monitoring",
        auth_type="bearer",
        default_url="https://sentry.io/api/0",
        icon="sentry",
        category="observability",
        builtin_server_id="builtin-sentry",
        display_name="Sentry",
    ),
    ConnectorSpec(
        name="datadog",
        description="Datadog — metrics, APM, logs, monitors, alerts",
        auth_type="api_key",
        default_url="https://api.datadoghq.com",
        icon="datadog",
        category="observability",
        builtin_server_id="builtin-datadog",
        display_name="Datadog",
    ),
    ConnectorSpec(
        name="stripe",
        description="Stripe — payments, subscriptions, invoices, customers",
        auth_type="bearer",
        default_url="https://api.stripe.com",
        icon="stripe",
        category="finance",
        builtin_server_id="builtin-stripe",
        display_name="Stripe",
    ),
    # ── CRM / Support ────────────────────────────────────────────────────────
    ConnectorSpec(
        name="hubspot",
        description="HubSpot — CRM, contacts, deals, marketing automation",
        auth_type="bearer",
        default_url="https://api.hubapi.com",
        icon="hubspot",
        category="crm",
        builtin_server_id="builtin-hubspot",
        display_name="HubSpot",
    ),
    ConnectorSpec(
        name="zendesk",
        description="Zendesk — customer support, tickets, agents, macros",
        auth_type="api_key",
        default_url="https://your-domain.zendesk.com/api/v2",
        icon="zendesk",
    ),
    ConnectorSpec(
        name="intercom",
        description="Intercom — customer messaging, conversations, contacts",
        auth_type="bearer",
        default_url="https://api.intercom.io",
        icon="intercom",
    ),
    # ── Cloud Providers ──────────────────────────────────────────────────────
    ConnectorSpec(
        name="aws",
        description="AWS — boto3-backed tools for S3, EC2, Lambda, IAM, CloudWatch",
        auth_type="api_key",
        default_url="https://aws.amazon.com",
        icon="aws",
    ),
    ConnectorSpec(
        name="gcp",
        description="GCP — Google Cloud Storage, BigQuery, Pub/Sub, Cloud Run",
        auth_type="oauth_ac",
        default_url="https://www.googleapis.com",
        icon="gcp",
    ),
    # ── Databases ────────────────────────────────────────────────────────────
    ConnectorSpec(
        name="postgresql",
        description="PostgreSQL — execute queries, inspect schema, manage tables",
        auth_type="connection_string",
        default_url="postgresql://localhost:5432/db",
        icon="postgresql",
        category="database",
        builtin_server_id="builtin-postgres",
        display_name="PostgreSQL",
    ),
    ConnectorSpec(
        name="mysql",
        description="MySQL — query execution, schema introspection, DML operations",
        auth_type="connection_string",
        default_url="mysql://localhost:3306/db",
        icon="mysql",
    ),
    ConnectorSpec(
        name="mongodb",
        description="MongoDB — documents CRUD, aggregations, index management",
        auth_type="connection_string",
        default_url="mongodb://localhost:27017",
        icon="mongodb",
    ),
    ConnectorSpec(
        name="snowflake",
        description="Snowflake — data warehouse queries, warehouses, schemas",
        auth_type="api_key",
        default_url="https://account.snowflakecomputing.com",
        icon="snowflake",
    ),
    # ── Productivity ─────────────────────────────────────────────────────────
    ConnectorSpec(
        name="google_sheets",
        description="Google Sheets — read/write spreadsheets, ranges, formulas",
        auth_type="oauth_ac",
        default_url="https://sheets.googleapis.com/v4",
        icon="google_sheets",
    ),
    ConnectorSpec(
        name="asana",
        description="Asana — tasks, projects, portfolios, team workspaces",
        auth_type="bearer",
        default_url="https://app.asana.com/api/1.0",
        icon="asana",
    ),
    ConnectorSpec(
        name="monday",
        description="Monday.com — boards, items, columns, automations",
        auth_type="bearer",
        default_url="https://api.monday.com/v2",
        icon="monday",
    ),
    # ── Communication ────────────────────────────────────────────────────────
    ConnectorSpec(
        name="teams",
        description="Microsoft Teams — messaging, channels, meetings, notifications",
        auth_type="oauth_ac",
        default_url="https://graph.microsoft.com/v1.0",
        icon="teams",
    ),
    ConnectorSpec(
        name="discord",
        description="Discord — community messaging, channels, webhooks",
        auth_type="bearer",
        default_url="https://discord.com/api/v10",
        icon="discord",
    ),
    ConnectorSpec(
        name="twilio",
        description="Twilio — SMS, voice, WhatsApp, email notifications",
        auth_type="basic",
        default_url="https://api.twilio.com/2010-04-01",
        icon="twilio",
    ),
    # ── Finance ──────────────────────────────────────────────────────────────
    ConnectorSpec(
        name="quickbooks",
        description="QuickBooks — accounting, invoicing, expense tracking",
        auth_type="oauth_ac",
        default_url="https://quickbooks.api.intuit.com/v3",
        icon="quickbooks",
    ),
    # ── Identity ─────────────────────────────────────────────────────────────
    ConnectorSpec(
        name="okta",
        description="Okta — identity, SSO, user provisioning, MFA",
        auth_type="api_key",
        default_url="https://your-domain.okta.com/api/v1",
        icon="okta",
    ),
    # ── DevOps / Infrastructure ──────────────────────────────────────────────
    ConnectorSpec(
        name="circleci",
        description="CircleCI — CI/CD pipelines, jobs, workflows, artifacts",
        auth_type="bearer",
        default_url="https://circleci.com/api/v2",
        icon="circleci",
    ),
    ConnectorSpec(
        name="terraform",
        description="Terraform Cloud — IaC workspaces, runs, state management",
        auth_type="bearer",
        default_url="https://app.terraform.io/api/v2",
        icon="terraform",
    ),
    ConnectorSpec(
        name="kubernetes",
        description="Kubernetes — pods, deployments, services, namespaces",
        auth_type="bearer",
        default_url="https://kubernetes.default.svc",
        icon="kubernetes",
    ),
    # ── Additional DevOps / Documentation ────────────────────────────────────
    ConnectorSpec(
        name="gitlab",
        description="GitLab — repositories, CI/CD pipelines, merge requests, issues",
        auth_type="bearer",
        default_url="https://gitlab.com/api/v4",
        icon="gitlab",
        category="devtools",
        builtin_server_id="builtin-gitlab",
        display_name="GitLab",
    ),
    ConnectorSpec(
        name="pagerduty",
        description="PagerDuty — incident management, on-call schedules, alerts",
        auth_type="api_key",
        default_url="https://api.pagerduty.com",
        icon="pagerduty",
    ),
    ConnectorSpec(
        name="confluence",
        description="Confluence — wiki pages, spaces, team knowledge base",
        auth_type="basic",
        default_url="https://your-domain.atlassian.net/wiki/rest/api",
        icon="confluence",
        category="project_management",
        builtin_server_id="builtin-confluence",
        display_name="Confluence",
    ),
    # Email Marketing
    ConnectorSpec(
        name="activecampaign",
        description="ActiveCampaign — email marketing & CRM contacts, lists, and campaigns",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="activecampaign",
    ),
    ConnectorSpec(
        name="aweber",
        description="AWeber — email marketing subscribers, lists, and broadcasts",
        auth_type="bearer",
        default_url="https://api.aweber.com/1.0",
        icon="aweber",
    ),
    ConnectorSpec(
        name="campaign_monitor",
        description="Campaign Monitor — email campaigns, subscriber lists, and delivery stats",
        auth_type="api_key",
        default_url="https://api.createsend.com/api/v3.3",
        icon="campaign_monitor",
    ),
    ConnectorSpec(
        name="constant_contact",
        description="Constant Contact — email marketing contacts, lists, and campaigns",
        auth_type="api_key",
        default_url="https://api.cc.email/v3",
        icon="constant_contact",
    ),
    ConnectorSpec(
        name="drip",
        description="Drip — ecommerce CRM, subscriber management, and email automation",
        auth_type="api_key",
        default_url="https://api.getdrip.com/v2",
        icon="drip",
    ),
    ConnectorSpec(
        name="getresponse",
        description="GetResponse — email marketing contacts, campaigns, and statistics",
        auth_type="api_key",
        default_url="https://api.getresponse.com/v3",
        icon="getresponse",
    ),
    ConnectorSpec(
        name="mailgun",
        description="Mailgun — transactional email sending, domain management, and event logs",
        auth_type="api_key",
        default_url="https://api.mailgun.net/v3",
        icon="mailgun",
    ),
    ConnectorSpec(
        name="moosend",
        description="Moosend — email marketing lists, subscribers, and campaigns",
        auth_type="api_key",
        default_url="https://api.moosend.com/v3",
        icon="moosend",
    ),
    ConnectorSpec(
        name="omnisend",
        description="Omnisend — omnichannel marketing contacts, segments, campaigns, and event tracking",
        auth_type="api_key",
        default_url="https://api.omnisend.com/v3",
        icon="omnisend",
    ),
    ConnectorSpec(
        name="loops",
        description="Loops — transactional and marketing email for SaaS products",
        auth_type="api_key",
        default_url="https://app.loops.so/api/v1",
        icon="loops",
    ),
    ConnectorSpec(
        name="acoustic",
        description="Acoustic (IBM) Marketing Cloud — campaigns, contacts, and email sends",
        auth_type="oauth_ac",
        default_url="https://api-campaign-us-6.goacoustic.com",
        icon="acoustic",
    ),
    ConnectorSpec(
        name="autopilot",
        description="Autopilot (Ortto) — marketing automation, journeys, and contact management",
        auth_type="api_key",
        default_url="https://api2.autopilothq.com/v1",
        icon="autopilot",
    ),
    ConnectorSpec(
        name="egoi",
        description="E-goi — multi-channel marketing with SMS, email, and push notifications",
        auth_type="api_key",
        default_url="https://api.egoiapp.com",
        icon="egoi",
    ),
    ConnectorSpec(
        name="emarsys",
        description="Emarsys — marketing platform with contacts, campaigns, and analytics",
        auth_type="api_key",
        default_url="https://api.emarsys.net/api/v2",
        icon="emarsys",
    ),
    ConnectorSpec(
        name="emma",
        description="Emma email marketing — contacts, groups, mailings, and analytics",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="emma",
    ),
    ConnectorSpec(
        name="esputnik",
        description="eSputnik — omnichannel marketing automation and contact management",
        auth_type="api_key",
        default_url="https://esputnik.com/api/v1",
        icon="esputnik",
    ),
    ConnectorSpec(
        name="maropost",
        description="Maropost — email marketing, contact management, and campaign analytics",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="maropost",
    ),
    # Chat, Push & Messaging
    ConnectorSpec(
        name="manychat",
        description="ManyChat — chat marketing subscriber management and content delivery",
        auth_type="api_key",
        default_url="https://api.manychat.com/fb",
        icon="manychat",
    ),
    ConnectorSpec(
        name="onesignal",
        description="OneSignal — push notifications, device management, and segments",
        auth_type="api_key",
        default_url="https://onesignal.com/api/v1",
        icon="onesignal",
    ),
    ConnectorSpec(
        name="pushover",
        description="Pushover — push notifications to mobile devices and desktop clients",
        auth_type="api_key",
        default_url="https://api.pushover.net/1",
        icon="pushover",
    ),
    ConnectorSpec(
        name="pushbullet",
        description="Pushbullet — push notifications, links, notes, and file sharing to devices",
        auth_type="api_key",
        default_url="https://api.pushbullet.com/v2",
        icon="pushbullet",
    ),
    ConnectorSpec(
        name="chatfuel",
        description="Chatfuel — chatbot platform for Facebook Messenger and Instagram",
        auth_type="api_key",
        default_url="https://api.chatfuel.com",
        icon="chatfuel",
    ),
    ConnectorSpec(
        name="ringcentral",
        description="RingCentral — cloud communications: SMS, voice calls, and message management",
        auth_type="bearer",
        default_url="https://platform.ringcentral.com/restapi/v1.0",
        icon="ringcentral",
    ),
    ConnectorSpec(
        name="plivo",
        description="Plivo — cloud communications: SMS, voice calls, and phone number management",
        auth_type="api_key",
        default_url="https://api.plivo.com/v1",
        icon="plivo",
    ),
    ConnectorSpec(
        name="vonage",
        description="Vonage (Nexmo) — SMS messaging, voice calls, and account management",
        auth_type="api_key",
        default_url="https://rest.nexmo.com",
        icon="vonage",
    ),
    ConnectorSpec(
        name="google_chat",
        description="Google Chat — send messages and manage Chat spaces",
        auth_type="bearer",
        default_url="https://chat.googleapis.com/v1",
        icon="google_chat",
    ),
    ConnectorSpec(
        name="google_meet",
        description="Google Meet — create and manage video meetings",
        auth_type="bearer",
        default_url="https://meet.googleapis.com/v2",
        icon="google_meet",
    ),
    # Transactional Email
    ConnectorSpec(
        name="postmark",
        description="Postmark — transactional email sending, templates, streams, bounces, and stats",
        auth_type="api_key",
        default_url="https://api.postmarkapp.com",
        icon="postmark",
    ),
    ConnectorSpec(
        name="amazon_ses",
        description="Amazon SES — email delivery via SES API",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="amazon_ses",
    ),
    # CRM & Sales (extended)
    ConnectorSpec(
        name="airtable",
        description="Airtable — database records management across bases and tables",
        auth_type="api_key",
        default_url="https://api.airtable.com/v0",
        icon="airtable",
    ),
    ConnectorSpec(
        name="capsule_crm",
        description="Capsule CRM — contacts, opportunities, and notes management",
        auth_type="api_key",
        default_url="https://api.capsulecrm.com/api/v2",
        icon="capsule_crm",
    ),
    ConnectorSpec(
        name="clearbit",
        description="Clearbit — person/company enrichment, email lookup, and IP reveal",
        auth_type="api_key",
        default_url="https://person.clearbit.com/v2",
        icon="clearbit",
    ),
    ConnectorSpec(
        name="dynamics365",
        description="Microsoft Dynamics 365 CRM — accounts, contacts, and leads management",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="dynamics365",
    ),
    ConnectorSpec(
        name="encharge",
        description="Encharge — marketing automation: users, tags, events, and segments",
        auth_type="api_key",
        default_url="https://api.encharge.io/v1",
        icon="encharge",
    ),
    ConnectorSpec(
        name="freshsales",
        description="Freshsales CRM — contacts, deals, and accounts management",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="freshsales",
    ),
    ConnectorSpec(
        name="fullcontact",
        description="FullContact — person/company enrichment, tag management, and contact creation",
        auth_type="api_key",
        default_url="https://api.fullcontact.com/v3",
        icon="fullcontact",
    ),
    ConnectorSpec(
        name="gainsight",
        description="Gainsight — customer success: accounts, CSMs, CTAs, and scorecards",
        auth_type="api_key",
        default_url="https://api.gainsight.com/v1",
        icon="gainsight",
    ),
    ConnectorSpec(
        name="highlevel",
        description="GoHighLevel CRM — contacts, campaigns, pipelines, opportunities, and SMS",
        auth_type="api_key",
        default_url="https://rest.gohighlevel.com/v1",
        icon="highlevel",
    ),
    ConnectorSpec(
        name="hubspot_marketing",
        description="HubSpot Marketing Hub — forms, email campaigns, lists, and analytics",
        auth_type="api_key",
        default_url="https://api.hubapi.com",
        icon="hubspot_marketing",
    ),
    ConnectorSpec(
        name="insightly",
        description="Insightly CRM — contacts, opportunities, projects, and tasks",
        auth_type="api_key",
        default_url="https://api.insight.ly/v3.1",
        icon="insightly",
    ),
    ConnectorSpec(
        name="klenty",
        description="Klenty — sales engagement: prospects, cadences, and email analytics",
        auth_type="api_key",
        default_url="https://app.klenty.com/apis/v1",
        icon="klenty",
    ),
    ConnectorSpec(
        name="konnektive",
        description="Konnektive CRM — orders, customers, and subscriptions management",
        auth_type="api_key",
        default_url="https://api.konnektive.com",
        icon="konnektive",
    ),
    ConnectorSpec(
        name="leadpages",
        description="Leadpages — landing pages, leads, lead boxes, and conversion analytics",
        auth_type="api_key",
        default_url="https://api.leadpages.io/v1",
        icon="leadpages",
    ),
    ConnectorSpec(
        name="lemlist",
        description="Lemlist — sales outreach: campaigns, leads, and engagement analytics",
        auth_type="api_key",
        default_url="https://api.lemlist.com/api",
        icon="lemlist",
    ),
    ConnectorSpec(
        name="outreach",
        description="Outreach — sales engagement: prospects, sequences, and analytics",
        auth_type="bearer",
        default_url="https://api.outreach.io/api/v2",
        icon="outreach",
    ),
    ConnectorSpec(
        name="overloop",
        description="Overloop (ex-Prospect.io) — outreach prospecting and sequence management",
        auth_type="api_key",
        default_url="https://app.overloop.com/api/v1",
        icon="overloop",
    ),
    ConnectorSpec(
        name="reply_io",
        description="Reply.io — sales automation: people, sequences, and email statistics",
        auth_type="api_key",
        default_url="https://api.reply.io/v1",
        icon="reply_io",
    ),
    ConnectorSpec(
        name="salesloft",
        description="Salesloft — sales engagement: people, cadences, calls, and analytics",
        auth_type="api_key",
        default_url="https://api.salesloft.com/v2",
        icon="salesloft",
    ),
    ConnectorSpec(
        name="segment",
        description="Segment — customer data platform: identify, track, page, group, and alias",
        auth_type="api_key",
        default_url="https://api.segment.io/v1",
        icon="segment",
    ),
    ConnectorSpec(
        name="snovio",
        description="Snov.io — lead generation: email finding, verification, and prospect management",
        auth_type="oauth_ac",
        default_url="https://api.snov.io",
        icon="snovio",
    ),
    ConnectorSpec(
        name="sugarcrm",
        description="SugarCRM — accounts, contacts, and leads management",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="sugarcrm",
    ),
    ConnectorSpec(
        name="vero",
        description="Vero — email & push: user identification, event tracking, and campaigns",
        auth_type="api_key",
        default_url="https://api.getvero.com/api/v2",
        icon="vero",
    ),
    ConnectorSpec(
        name="podio",
        description="Podio — project management: apps, items, spaces, and tasks",
        auth_type="bearer",
        default_url="https://api.podio.com",
        icon="podio",
    ),
    ConnectorSpec(
        name="orbit",
        description="Orbit — community management: members, activities, and workspace analytics",
        auth_type="api_key",
        default_url="https://app.orbit.love/api/v1",
        icon="orbit",
    ),
    # Time Tracking & Project Management
    ConnectorSpec(
        name="clockify",
        description="Clockify — time tracking, projects, workspaces, and reports",
        auth_type="api_key",
        default_url="https://api.clockify.me/api/v1",
        icon="clockify",
    ),
    ConnectorSpec(
        name="toggl",
        description="Toggl Track — time tracking, projects, clients, and reports",
        auth_type="api_key",
        default_url="https://api.track.toggl.com/api/v9",
        icon="toggl",
    ),
    ConnectorSpec(
        name="harvest",
        description="Harvest — time tracking, expense management, projects, and invoicing",
        auth_type="bearer",
        default_url="https://api.harvestapp.com/v2",
        icon="harvest",
    ),
    ConnectorSpec(
        name="teamwork",
        description="Teamwork — project management, tasks, and milestones",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="teamwork",
    ),
    ConnectorSpec(
        name="hive",
        description="Hive — project and action management, workspaces, and collaboration",
        auth_type="api_key",
        default_url="https://app.hive.com/api/v1",
        icon="hive",
    ),
    ConnectorSpec(
        name="pivotal_tracker",
        description="Pivotal Tracker — agile stories, projects, and iterations",
        auth_type="api_key",
        default_url="https://www.pivotaltracker.com/services/v5",
        icon="pivotal_tracker",
    ),
    ConnectorSpec(
        name="redmine",
        description="Redmine — issue tracking, projects, users, and time entries",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="redmine",
    ),
    ConnectorSpec(
        name="procore",
        description="Procore — construction management, projects, RFIs, submittals, and budgets",
        auth_type="bearer",
        default_url="https://api.procore.com/rest/v1.0",
        icon="procore",
    ),
    ConnectorSpec(
        name="ninox",
        description="Ninox — database management, tables, and records",
        auth_type="api_key",
        default_url="https://api.ninox.com/v1",
        icon="ninox",
    ),
    ConnectorSpec(
        name="knack",
        description="Knack — no-code database records, objects, and views",
        auth_type="api_key",
        default_url="https://api.knack.com/v1",
        icon="knack",
    ),
    ConnectorSpec(
        name="smartsheets",
        description="Smartsheet — project management sheets, rows, and reports",
        auth_type="bearer",
        default_url="https://api.smartsheet.com/2.0",
        icon="smartsheets",
    ),
    ConnectorSpec(
        name="miro",
        description="Miro — visual collaboration boards, sticky notes, frames, and items",
        auth_type="bearer",
        default_url="https://api.miro.com/v2",
        icon="miro",
    ),
    # HR, Recruiting & Payroll
    ConnectorSpec(
        name="greenhouse",
        description="Greenhouse — applicant tracking, jobs, candidates, and applications",
        auth_type="api_key",
        default_url="https://harvest.greenhouse.io/v1",
        icon="greenhouse",
    ),
    ConnectorSpec(
        name="recruitee",
        description="Recruitee — applicant tracking, candidates, offers, and stages",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="recruitee",
    ),
    ConnectorSpec(
        name="gusto",
        description="Gusto — payroll, HR, employees, pay periods, and benefits",
        auth_type="bearer",
        default_url="https://api.gusto.com/v1",
        icon="gusto",
    ),
    # Finance & Accounting (extended)
    ConnectorSpec(
        name="freshbooks",
        description="FreshBooks — accounting, invoices, clients, and expenses",
        auth_type="bearer",
        default_url="https://api.freshbooks.com",
        icon="freshbooks",
    ),
    ConnectorSpec(
        name="wave",
        description="Wave — accounting, invoices, customers, and transactions via GraphQL",
        auth_type="bearer",
        default_url="https://gql.waveapps.com/graphql/public",
        icon="wave",
    ),
    ConnectorSpec(
        name="invoice_ninja",
        description="Invoice Ninja — invoicing, clients, and payments",
        auth_type="api_key",
        default_url="https://app.invoiceninja.com/api/v1",
        icon="invoice_ninja",
    ),
    ConnectorSpec(
        name="netsuite",
        description="NetSuite — ERP records, search, and saved searches via REST API",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="netsuite",
    ),
    ConnectorSpec(
        name="braintree",
        description="Braintree — payment transactions, customers, and subscriptions",
        auth_type="api_key",
        default_url="https://api.braintreegateway.com",
        icon="braintree",
    ),
    ConnectorSpec(
        name="samcart",
        description="SamCart — checkout platform products, orders, and customers",
        auth_type="api_key",
        default_url="https://api.samcart.com/v1",
        icon="samcart",
    ),
    ConnectorSpec(
        name="profitwell",
        description="ProfitWell — subscription metrics, MRR, churn, and customer analytics",
        auth_type="api_key",
        default_url="https://api.profitwell.com/v2",
        icon="profitwell",
    ),
    ConnectorSpec(
        name="zuora",
        description="Zuora — subscription billing, accounts, invoices, and subscriptions",
        auth_type="oauth_ac",
        default_url="https://rest.zuora.com/v1",
        icon="zuora",
    ),
    ConnectorSpec(
        name="zoho_books",
        description="Zoho Books — accounting, invoices, contacts, and expenses",
        auth_type="bearer",
        default_url="https://www.zohoapis.com/books/v3",
        icon="zoho_books",
    ),
    ConnectorSpec(
        name="zoho_invoice",
        description="Zoho Invoice — invoicing, customers, and invoice lifecycle",
        auth_type="bearer",
        default_url="https://www.zohoapis.com/invoice/v3",
        icon="zoho_invoice",
    ),
    ConnectorSpec(
        name="plaid",
        description="Plaid — financial data aggregation and bank account access",
        auth_type="bearer",
        default_url="https://production.plaid.com",
        icon="plaid",
    ),
    ConnectorSpec(
        name="alpaca",
        description="Alpaca — commission-free trading, market data, and portfolio management",
        auth_type="api_key",
        default_url="https://api.alpaca.markets/v2",
        icon="alpaca",
    ),
    ConnectorSpec(
        name="brex",
        description="Brex — corporate card management, transactions, and expense tracking",
        auth_type="api_key",
        default_url="https://platform.brexapis.com",
        icon="brex",
    ),
    ConnectorSpec(
        name="ramp",
        description="Ramp — corporate spend management, cards, and transaction approval",
        auth_type="bearer",
        default_url="https://api.ramp.com/developer/v1",
        icon="ramp",
    ),
    # E-commerce (extended)
    ConnectorSpec(
        name="etsy",
        description="Etsy — Etsy marketplace shops, listings, and orders management",
        auth_type="bearer",
        default_url="https://openapi.etsy.com/v3",
        icon="etsy",
    ),
    ConnectorSpec(
        name="ebay",
        description="eBay — eBay marketplace item search, orders, and selling statistics",
        auth_type="bearer",
        default_url="https://api.ebay.com/buy/browse/v1",
        icon="ebay",
    ),
    ConnectorSpec(
        name="ecwid",
        description="Ecwid — Ecwid e-commerce store products, orders, and statistics",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="ecwid",
    ),
    ConnectorSpec(
        name="magento",
        description="Magento — Magento e-commerce products, orders, customers, and categories",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="magento",
    ),
    ConnectorSpec(
        name="squarespace",
        description="Squarespace — Squarespace website pages, products, orders, and inventory",
        auth_type="api_key",
        default_url="https://api.squarespace.com/1.0",
        icon="squarespace",
    ),
    ConnectorSpec(
        name="lightspeed",
        description="Lightspeed — Lightspeed Retail POS products, sales, customers, and inventory",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="lightspeed",
    ),
    ConnectorSpec(
        name="shipstation",
        description="ShipStation — ShipStation shipping, orders, shipments, and labels",
        auth_type="api_key",
        default_url="https://ssapi.shipstation.com",
        icon="shipstation",
    ),
    ConnectorSpec(
        name="order_desk",
        description="Order Desk — Order Desk order management, inventory, and shipments",
        auth_type="api_key",
        default_url="https://app.orderdesk.me/api/v2",
        icon="order_desk",
    ),
    ConnectorSpec(
        name="yotpo",
        description="Yotpo — Yotpo reviews, loyalty points, and marketing campaigns",
        auth_type="api_key",
        default_url="https://api.yotpo.com/core/v3",
        icon="yotpo",
    ),
    ConnectorSpec(
        name="gumroad",
        description="Gumroad — Gumroad digital product sales, subscriptions, and license management",
        auth_type="bearer",
        default_url="https://api.gumroad.com/v2",
        icon="gumroad",
    ),
    ConnectorSpec(
        name="kajabi",
        description="Kajabi — Kajabi online courses, members, offers, and pipeline management",
        auth_type="api_key",
        default_url="https://kajabi.com/api/v1",
        icon="kajabi",
    ),
    ConnectorSpec(
        name="teachable",
        description="Teachable — Teachable online course users, enrollments, coupons, and progress",
        auth_type="api_key",
        default_url="https://developers.teachable.com/v1",
        icon="teachable",
    ),
    ConnectorSpec(
        name="thinkific",
        description="Thinkific — Thinkific online courses, users, enrollments, and stats",
        auth_type="api_key",
        default_url="https://api.thinkific.com/api/public/v1",
        icon="thinkific",
    ),
    ConnectorSpec(
        name="thrivecart",
        description="ThriveCart — checkout platform, products, orders, and affiliates",
        auth_type="api_key",
        default_url="https://thrivecart.com/api/external/v1",
        icon="thrivecart",
    ),
    ConnectorSpec(
        name="clickfunnels",
        description="ClickFunnels — sales funnel management, contacts, and orders",
        auth_type="api_key",
        default_url="https://app.clickfunnels.com/api/v2",
        icon="clickfunnels",
    ),
    ConnectorSpec(
        name="digistore24",
        description="Digistore24 — digital marketplace orders, products, and commissions",
        auth_type="api_key",
        default_url="https://www.digistore24.com/api/call",
        icon="digistore24",
    ),
    # Content, CMS & Publishing
    ConnectorSpec(
        name="substack",
        description="Substack — Substack newsletter posts, subscribers, stats, and email sends",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="substack",
    ),
    ConnectorSpec(
        name="storyblok",
        description="Storyblok — Storyblok headless CMS stories, components, and publishing",
        auth_type="bearer",
        default_url="https://mapi.storyblok.com/v1",
        icon="storyblok",
    ),
    ConnectorSpec(
        name="vimeo",
        description="Vimeo — Vimeo video hosting, uploads, folders, and analytics",
        auth_type="bearer",
        default_url="https://api.vimeo.com",
        icon="vimeo",
    ),
    ConnectorSpec(
        name="wistia",
        description="Wistia — Wistia video hosting, media management, and analytics",
        auth_type="api_key",
        default_url="https://api.wistia.com/v1",
        icon="wistia",
    ),
    ConnectorSpec(
        name="loom",
        description="Loom — video messaging via Loom API v1",
        auth_type="api_key",
        default_url="https://api.loom.com/v1",
        icon="loom",
    ),
    ConnectorSpec(
        name="feedly",
        description="Feedly — news aggregation, RSS stream reading, and article management",
        auth_type="bearer",
        default_url="https://cloud.feedly.com/v3",
        icon="feedly",
    ),
    ConnectorSpec(
        name="evernote",
        description="Evernote — note-taking, notebooks, and search via Evernote API",
        auth_type="bearer",
        default_url="https://www.evernote.com/edam/note",
        icon="evernote",
    ),
    # Social Media (extended)
    ConnectorSpec(
        name="spotify",
        description="Spotify — Spotify music track search, playlists, and artist info",
        auth_type="bearer",
        default_url="https://api.spotify.com/v1",
        icon="spotify",
    ),
    ConnectorSpec(
        name="pinterest",
        description="Pinterest — Pinterest boards, pins, analytics, and search",
        auth_type="bearer",
        default_url="https://api.pinterest.com/v5",
        icon="pinterest",
    ),
    ConnectorSpec(
        name="hootsuite",
        description="Hootsuite — Hootsuite social media profile management, scheduling, and analytics",
        auth_type="bearer",
        default_url="https://platform.hootsuite.com/v1",
        icon="hootsuite",
    ),
    ConnectorSpec(
        name="sprout_social",
        description="Sprout Social — Sprout Social social media management, analytics, and tasks",
        auth_type="bearer",
        default_url="https://api.sproutsocial.com/v1",
        icon="sprout_social",
    ),
    ConnectorSpec(
        name="buffer",
        description="Buffer — Buffer social media post scheduling, analytics, and profile management",
        auth_type="bearer",
        default_url="https://api.bufferapp.com/1",
        icon="buffer",
    ),
    ConnectorSpec(
        name="facebook_pages",
        description="Facebook Pages — Facebook Page posts, insights, comments, and scheduling",
        auth_type="bearer",
        default_url="https://graph.facebook.com/v18.0",
        icon="facebook_pages",
    ),
    ConnectorSpec(
        name="facebook_lead_ads",
        description="Facebook Lead Ads — Facebook Lead Ad forms, leads, ad accounts, and insights",
        auth_type="bearer",
        default_url="https://graph.facebook.com/v18.0",
        icon="facebook_lead_ads",
    ),
    ConnectorSpec(
        name="facebook_conversions",
        description="Facebook Conversions — Facebook Conversions API server-side event tracking",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="facebook_conversions",
    ),
    ConnectorSpec(
        name="twitch",
        description="Twitch — streaming platform: streams, users, followers, videos, and channels",
        auth_type="bearer",
        default_url="https://api.twitch.tv/helix",
        icon="twitch",
    ),
    # Cloud & Developer Tools (extended)
    ConnectorSpec(
        name="amazon_sqs",
        description="Amazon SQS — message queue operations via SQS API",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="amazon_sqs",
    ),
    ConnectorSpec(
        name="apache_kafka",
        description="Apache Kafka — topic and consumer-group management via Confluent Cloud REST Proxy",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="apache_kafka",
    ),
    ConnectorSpec(
        name="bigquery",
        description="Google BigQuery — data warehouse queries and management",
        auth_type="bearer",
        default_url="https://bigquery.googleapis.com/bigquery/v2",
        icon="bigquery",
    ),
    ConnectorSpec(
        name="cloudflare",
        description="Cloudflare — CDN, DNS, and Workers management via Cloudflare API v4",
        auth_type="api_key",
        default_url="https://api.cloudflare.com/client/v4",
        icon="cloudflare",
    ),
    ConnectorSpec(
        name="cloudinary",
        description="Cloudinary — media upload, transformation, and management",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="cloudinary",
    ),
    ConnectorSpec(
        name="firebase",
        description="Firebase / Firestore — document database and push notifications",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="firebase",
    ),
    ConnectorSpec(
        name="figma",
        description="Figma — design file access and collaboration via Figma API",
        auth_type="bearer",
        default_url="https://api.figma.com/v1",
        icon="figma",
    ),
    ConnectorSpec(
        name="filestack",
        description="Filestack — file upload, transformation, and management",
        auth_type="api_key",
        default_url="https://www.filestackapi.com/api",
        icon="filestack",
    ),
    ConnectorSpec(
        name="sonarqube",
        description="SonarQube — code quality and security analysis",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="sonarqube",
    ),
    ConnectorSpec(
        name="bitly",
        description="Bitly — URL shortening and click analytics",
        auth_type="bearer",
        default_url="https://api-ssl.bitly.com/v4",
        icon="bitly",
    ),
    ConnectorSpec(
        name="gemini",
        description="Google Gemini — multimodal AI text generation and embeddings",
        auth_type="api_key",
        default_url="https://generativelanguage.googleapis.com/v1",
        icon="gemini",
    ),
    ConnectorSpec(
        name="elevenlabs",
        description="ElevenLabs — AI text-to-speech and voice cloning",
        auth_type="api_key",
        default_url="https://api.elevenlabs.io/v1",
        icon="elevenlabs",
    ),
    ConnectorSpec(
        name="appsheet",
        description="AppSheet — no-code app data management and action invocation",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="appsheet",
    ),
    ConnectorSpec(
        name="anvil",
        description="Anvil — PDF generation, form filling, and e-signature workflows",
        auth_type="api_key",
        default_url="https://app.useanvil.com/api/v1",
        icon="anvil",
    ),
    # Forms & Surveys
    ConnectorSpec(
        name="typeform",
        description="Typeform — form building and response collection",
        auth_type="bearer",
        default_url="https://api.typeform.com",
        icon="typeform",
    ),
    ConnectorSpec(
        name="jotform",
        description="JotForm — form building and submission management",
        auth_type="api_key",
        default_url="https://api.jotform.com",
        icon="jotform",
    ),
    ConnectorSpec(
        name="surveymonkey",
        description="SurveyMonkey — survey creation and response analysis",
        auth_type="bearer",
        default_url="https://api.surveymonkey.com/v3",
        icon="surveymonkey",
    ),
    ConnectorSpec(
        name="formstack",
        description="Formstack — forms, submissions, and documents",
        auth_type="api_key",
        default_url="https://www.formstack.com/api/v2",
        icon="formstack",
    ),
    ConnectorSpec(
        name="signnow",
        description="SignNow — electronic signature management",
        auth_type="bearer",
        default_url="https://api.signnow.com",
        icon="signnow",
    ),
    ConnectorSpec(
        name="wufoo",
        description="Wufoo — form building, entries, and report data",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="wufoo",
    ),
    ConnectorSpec(
        name="gravity_forms",
        description="Gravity Forms — WordPress form builder data and submissions",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="gravity_forms",
    ),
    # Microsoft 365 (extended)
    ConnectorSpec(
        name="microsoft_excel",
        description="Microsoft Excel — workbook and spreadsheet management via Microsoft Graph API",
        auth_type="bearer",
        default_url="https://graph.microsoft.com/v1.0",
        icon="microsoft_excel",
    ),
    ConnectorSpec(
        name="microsoft_outlook",
        description="Microsoft Outlook — email management via Microsoft Graph API",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="microsoft_outlook",
    ),
    ConnectorSpec(
        name="microsoft_onenote",
        description="Microsoft OneNote — notebook and page management via Microsoft Graph API",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="microsoft_onenote",
    ),
    ConnectorSpec(
        name="microsoft_todo",
        description="Microsoft To Do — task list management via Microsoft Graph API",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="microsoft_todo",
    ),
    # Google Workspace (extended)
    ConnectorSpec(
        name="gmail",
        description="Gmail — email reading, sending, drafts, and label management via Google APIs",
        auth_type="bearer",
        default_url="https://gmail.googleapis.com/gmail/v1",
        icon="gmail",
    ),
    ConnectorSpec(
        name="google_contacts",
        description="Google Contacts — manage contacts via the People API",
        auth_type="bearer",
        default_url="https://people.googleapis.com/v1",
        icon="google_contacts",
    ),
    ConnectorSpec(
        name="google_forms",
        description="Google Forms — form creation and response management via Google Forms API",
        auth_type="bearer",
        default_url="https://forms.googleapis.com/v1",
        icon="google_forms",
    ),
    ConnectorSpec(
        name="google_my_business",
        description="Google My Business — manage business locations, reviews, and insights",
        auth_type="bearer",
        default_url="https://mybusinessaccountmanagement.googleapis.com/v1",
        icon="google_my_business",
    ),
    ConnectorSpec(
        name="google_photos",
        description="Google Photos — manage photo library, albums, and media items",
        auth_type="bearer",
        default_url="https://photoslibrary.googleapis.com/v1",
        icon="google_photos",
    ),
    ConnectorSpec(
        name="google_slides",
        description="Google Slides — presentation management via Google Slides API v1",
        auth_type="bearer",
        default_url="https://slides.googleapis.com/v1",
        icon="google_slides",
    ),
    ConnectorSpec(
        name="google_tasks",
        description="Google Tasks — task list and task management via Google Tasks API v1",
        auth_type="bearer",
        default_url="https://tasks.googleapis.com/tasks/v1",
        icon="google_tasks",
    ),
    # Analytics & Business Intelligence
    ConnectorSpec(
        name="databox",
        description="Databox — business analytics dashboards and KPI tracking",
        auth_type="api_key",
        default_url="https://push.databox.com",
        icon="databox",
    ),
    ConnectorSpec(
        name="geckoboard",
        description="Geckoboard — business dashboards and dataset management",
        auth_type="api_key",
        default_url="https://api.geckoboard.com",
        icon="geckoboard",
    ),
    ConnectorSpec(
        name="fireflies",
        description="Fireflies.ai — meeting transcription and conversation intelligence",
        auth_type="api_key",
        default_url="https://api.fireflies.ai/graphql",
        icon="fireflies",
    ),
    ConnectorSpec(
        name="phantombuster",
        description="PhantomBuster — web automation and lead generation with Phantoms",
        auth_type="api_key",
        default_url="https://api.phantombuster.com/api/v2",
        icon="phantombuster",
    ),
    ConnectorSpec(
        name="fitbit",
        description="Fitbit — fitness tracking, health data, and device management",
        auth_type="bearer",
        default_url="https://api.fitbit.com/1",
        icon="fitbit",
    ),
    # Events & Webinars
    ConnectorSpec(
        name="gotowebinar",
        description="GoToWebinar — webinar creation, registration, and analytics",
        auth_type="bearer",
        default_url="https://api.getgo.com/G2W/rest/v2",
        icon="gotowebinar",
    ),
    ConnectorSpec(
        name="livestorm",
        description="Livestorm — webinar and virtual event management",
        auth_type="api_key",
        default_url="https://api.livestorm.co/v1",
        icon="livestorm",
    ),
    ConnectorSpec(
        name="eventbrite",
        description="Eventbrite — event creation, ticketing, and attendee management",
        auth_type="api_key",
        default_url="https://www.eventbriteapi.com/v3",
        icon="eventbrite",
    ),
    ConnectorSpec(
        name="meetup",
        description="Meetup — group events, RSVPs, and community management",
        auth_type="bearer",
        default_url="https://api.meetup.com",
        icon="meetup",
    ),
    ConnectorSpec(
        name="easywebinar",
        description="EasyWebinar — automated webinar hosting and attendee management",
        auth_type="api_key",
        default_url="https://easywebinar.com/api/v1",
        icon="easywebinar",
    ),
    # Customer Support (extended)
    ConnectorSpec(
        name="freshchat",
        description="Freshchat — modern customer messaging and live chat support",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="freshchat",
    ),
    ConnectorSpec(
        name="zoho_desk",
        description="Zoho Desk — customer support ticketing and helpdesk management",
        auth_type="bearer",
        default_url="https://desk.zoho.com/api/v1",
        icon="zoho_desk",
    ),
    ConnectorSpec(
        name="help_scout",
        description="Help Scout — customer support conversations and mailbox management",
        auth_type="api_key",
        default_url="https://api.helpscout.net/v2",
        icon="help_scout",
    ),
    ConnectorSpec(
        name="delighted",
        description="Delighted — customer satisfaction surveys and NPS tracking",
        auth_type="api_key",
        default_url="https://api.delighted.com/v1",
        icon="delighted",
    ),
    ConnectorSpec(
        name="zenloop",
        description="Zenloop — NPS surveys, feedback collection, and customer sentiment",
        auth_type="api_key",
        default_url="https://api.zenloop.com/v1",
        icon="zenloop",
    ),
    # Healthcare & Legal
    ConnectorSpec(
        name="epic_fhir",
        description="Epic EHR FHIR R4 — access patient data via FHIR R4 API",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="epic_fhir",
    ),
    ConnectorSpec(
        name="athenahealth",
        description="Athenahealth EHR — patient records, appointments, and clinical data",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="athenahealth",
    ),
    ConnectorSpec(
        name="drchrono",
        description="DrChrono EHR — patient management, appointments, and clinical notes",
        auth_type="bearer",
        default_url="https://drchrono.com/api",
        icon="drchrono",
    ),
    ConnectorSpec(
        name="clio",
        description="Clio — legal practice management, matters, contacts, and time tracking",
        auth_type="bearer",
        default_url="https://app.clio.com/api/v4",
        icon="clio",
    ),
    ConnectorSpec(
        name="harvey",
        description="Harvey AI — AI-powered legal research, drafting, and document analysis",
        auth_type="api_key",
        default_url="https://api.harvey.ai/v1",
        icon="harvey",
    ),
    # Real Estate & Construction
    ConnectorSpec(
        name="zillow",
        description="Zillow — real estate search, property details, and market estimates",
        auth_type="api_key",
        default_url="https://api.bridgedataoutput.com/api/v2",
        icon="zillow",
    ),
    ConnectorSpec(
        name="buildium",
        description="Buildium — property management, leases, tenants, and financials",
        auth_type="oauth_ac",
        default_url="https://api.buildium.com/v1",
        icon="buildium",
    ),
    ConnectorSpec(
        name="beds24",
        description="Beds24 — vacation rental property management and bookings",
        auth_type="api_key",
        default_url="https://api.beds24.com/api/v2",
        icon="beds24",
    ),
    # Education
    ConnectorSpec(
        name="canvas_lms",
        description="Canvas LMS — course management, assignments, and student grading",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="canvas_lms",
    ),
    ConnectorSpec(
        name="moodle",
        description="Moodle — e-learning course management, users, and assignments",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="moodle",
    ),
    # IoT & Automation
    ConnectorSpec(
        name="home_assistant",
        description="Home Assistant — IoT smart home control and automation",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="home_assistant",
    ),
    ConnectorSpec(
        name="aws_iot",
        description="AWS IoT Core — device management, shadows, and message publishing",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="aws_iot",
    ),
    # Travel, Logistics & Food
    ConnectorSpec(
        name="amadeus",
        description="Amadeus — travel search, flight booking, and hotel discovery",
        auth_type="oauth_ac",
        default_url="https://api.amadeus.com/v2",
        icon="amadeus",
    ),
    ConnectorSpec(
        name="doordash",
        description="DoorDash Drive — on-demand delivery creation and management",
        auth_type="api_key",
        default_url="https://openapi.doordash.com",
        icon="doordash",
    ),
    ConnectorSpec(
        name="flexport",
        description="Flexport — supply chain logistics, shipments, and freight management",
        auth_type="api_key",
        default_url="https://api.flexport.com",
        icon="flexport",
    ),
    ConnectorSpec(
        name="toast_pos",
        description="Toast POS — restaurant orders, menu management, and payments",
        auth_type="oauth_ac",
        default_url="https://ws-api.toasttab.com",
        icon="toast_pos",
    ),
    # Blockchain & Web3
    ConnectorSpec(
        name="alchemy",
        description="Alchemy — blockchain data, NFTs, and Web3 development",
        auth_type="api_key",
        default_url="https://api.example.com",
        icon="alchemy",
    ),
    ConnectorSpec(
        name="moralis",
        description="Moralis Web3 — blockchain data, NFT collections, and wallet analytics",
        auth_type="api_key",
        default_url="https://deep-index.moralis.io/api/v2.2",
        icon="moralis",
    ),
    # Sports, Media & Entertainment
    ConnectorSpec(
        name="sportradar",
        description="Sportradar — live scores, schedules, team stats, and sports data",
        auth_type="api_key",
        default_url="https://api.sportradar.com",
        icon="sportradar",
    ),
    ConnectorSpec(
        name="steam",
        description="Steam — gaming platform data, player profiles, and game info",
        auth_type="api_key",
        default_url="https://api.steampowered.com",
        icon="steam",
    ),
    ConnectorSpec(
        name="ap_news",
        description="AP News — breaking news articles and media content search",
        auth_type="api_key",
        default_url="https://api.ap.org/media/v/content",
        icon="ap_news",
    ),
    # Enterprise & Misc
    ConnectorSpec(
        name="sap",
        description="SAP ERP — purchase orders, materials, inventory, and procurement",
        auth_type="oauth_ac",
        default_url="https://api.example.com",
        icon="sap",
    ),
    ConnectorSpec(
        name="channable",
        description="Channable — product feed management, channel publishing, and rules",
        auth_type="api_key",
        default_url="https://app.channable.com/api/v1",
        icon="channable",
    ),
    ConnectorSpec(
        name="gleam",
        description="Gleam.io — contest, giveaway, and viral marketing campaigns",
        auth_type="api_key",
        default_url="https://gleam.io/api/v1",
        icon="gleam",
    ),
    ConnectorSpec(
        name="gust",
        description="Gust — startup funding platform, investor profiles, and applications",
        auth_type="bearer",
        default_url="https://api.gust.com/api/v1",
        icon="gust",
    ),
    ConnectorSpec(
        name="koala",
        description="Koala intent data — visitor tracking, account signals, and firmographics",
        auth_type="api_key",
        default_url="https://api.getkoala.com/v1",
        icon="koala",
    ),
    ConnectorSpec(
        name="logmein",
        description="LogMeIn Rescue — remote access sessions and computer management",
        auth_type="api_key",
        default_url="https://secure.logmeinrescue.com/API",
        icon="logmein",
    ),
    ConnectorSpec(
        name="mendeley",
        description="Mendeley — academic research platform, documents, and groups",
        auth_type="bearer",
        default_url="https://api.mendeley.com",
        icon="mendeley",
    ),
    ConnectorSpec(
        name="upkeep",
        description="UpKeep — maintenance management, work orders, and asset tracking",
        auth_type="api_key",
        default_url="https://api.onupkeep.com/api/v2",
        icon="upkeep",
    ),
    ConnectorSpec(
        name="yandex",
        description="Yandex — translation, disk storage, metrica analytics, and geocoding",
        auth_type="bearer",
        default_url="https://api.example.com",
        icon="yandex",
    ),
    ConnectorSpec(
        name="unbounce",
        description="Unbounce — landing pages, lead capture, and conversion analytics",
        auth_type="api_key",
        default_url="https://api.unbounce.com",
        icon="unbounce",
    ),
    ConnectorSpec(
        name="upwork",
        description="Upwork — freelance jobs, proposals, contracts, and profiles",
        auth_type="bearer",
        default_url="https://www.upwork.com/api",
        icon="upwork",
    ),
    ConnectorSpec(
        name="elavon",
        description="Elavon — payment processing, transaction management, and batch operations",
        auth_type="api_key",
        default_url="https://api.elavon.com/merchant",
        icon="elavon",
    ),
]
