"""PhantomBuster MCP server — web automation and lead generation with Phantoms.

Environment:
  PHANTOMBUSTER_API_KEY: PhantomBuster API key for authentication
"""
from __future__ import annotations

import os
from typing import Any

import httpx

from app.observability.logging import get_logger

logger = get_logger(__name__)
BASE_URL = "https://api.phantombuster.com/api/v2"

TOOL_DEFINITIONS = [
    {
        "name": "phantombuster_list_agents",
        "description": "List all automation agents (Phantoms) in the PhantomBuster account",
        "parameters": {
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "description": "Maximum number of agents to return"},
                "offset": {"type": "integer", "description": "Pagination offset"},
            },
        },
    },
    {
        "name": "phantombuster_launch_agent",
        "description": "Launch a PhantomBuster agent to start an automation task",
        "parameters": {
            "type": "object",
            "properties": {
                "agent_id": {"type": "string", "description": "ID of the agent to launch"},
                "arguments": {"type": "object", "description": "Input arguments for the agent"},
                "save_argument": {"type": "boolean", "description": "Whether to save the argument for future launches"},
            },
            "required": ["agent_id"],
        },
    },
    {
        "name": "phantombuster_get_agent_output",
        "description": "Get the output data from a PhantomBuster agent's latest or specific execution",
        "parameters": {
            "type": "object",
            "properties": {
                "agent_id": {"type": "string", "description": "ID of the agent"},
                "container_id": {"type": "string", "description": "Specific container/execution ID"},
            },
            "required": ["agent_id"],
        },
    },
    {
        "name": "phantombuster_list_phantoms",
        "description": "List available Phantom templates from the PhantomBuster store",
        "parameters": {
            "type": "object",
            "properties": {
                "category": {"type": "string", "description": "Category filter (e.g. linkedin, twitter)"},
                "limit": {"type": "integer", "description": "Maximum results"},
            },
        },
    },
    {
        "name": "phantombuster_fetch_output",
        "description": "Fetch the result file (CSV or JSON) generated by a Phantom execution",
        "parameters": {
            "type": "object",
            "properties": {
                "agent_id": {"type": "string", "description": "ID of the agent"},
                "format": {"type": "string", "description": "Output format: json or csv"},
            },
            "required": ["agent_id"],
        },
    },
    {
        "name": "phantombuster_abort_agent",
        "description": "Abort a currently running PhantomBuster agent execution",
        "parameters": {
            "type": "object",
            "properties": {
                "agent_id": {"type": "string", "description": "ID of the agent to abort"},
            },
            "required": ["agent_id"],
        },
    },
]


async def call_tool(tool_name: str, arguments: dict[str, Any]) -> Any:
    api_key = os.getenv("PHANTOMBUSTER_API_KEY", "")
    if not api_key:
        return {"error": "PHANTOMBUSTER_API_KEY not configured"}

    headers = {"X-Phantombuster-Key": api_key, "Content-Type": "application/json"}
    async with httpx.AsyncClient(timeout=30) as client:
        try:
            if tool_name == "phantombuster_list_agents":
                params = {k: v for k, v in arguments.items() if v is not None}
                r = await client.get(f"{BASE_URL}/agents/fetch-all", headers=headers, params=params)
                r.raise_for_status()
                return r.json()

            if tool_name == "phantombuster_launch_agent":
                agent_id = arguments["agent_id"]
                payload: dict[str, Any] = {"id": agent_id}
                if "arguments" in arguments:
                    payload["arguments"] = arguments["arguments"]
                if "save_argument" in arguments:
                    payload["saveArgument"] = arguments["save_argument"]
                r = await client.post(f"{BASE_URL}/agents/launch", headers=headers, json=payload)
                r.raise_for_status()
                return r.json()

            if tool_name == "phantombuster_get_agent_output":
                params: dict[str, Any] = {"id": arguments["agent_id"]}
                if "container_id" in arguments:
                    params["containerId"] = arguments["container_id"]
                r = await client.get(f"{BASE_URL}/containers/fetch-output", headers=headers, params=params)
                r.raise_for_status()
                return r.json()

            if tool_name == "phantombuster_list_phantoms":
                params = {k: v for k, v in arguments.items() if v is not None}
                r = await client.get(f"{BASE_URL}/store/phantoms", headers=headers, params=params)
                r.raise_for_status()
                return r.json()

            if tool_name == "phantombuster_fetch_output":
                params = {"id": arguments["agent_id"]}
                if "format" in arguments:
                    params["format"] = arguments["format"]
                r = await client.get(f"{BASE_URL}/agents/fetch-output", headers=headers, params=params)
                r.raise_for_status()
                return r.json()

            if tool_name == "phantombuster_abort_agent":
                r = await client.post(
                    f"{BASE_URL}/agents/abort",
                    headers=headers,
                    json={"id": arguments["agent_id"]},
                )
                r.raise_for_status()
                return r.json()

            return {"error": f"Unknown tool: {tool_name}"}
        except httpx.HTTPStatusError as e:
            return {"error": f"HTTP {e.response.status_code}: {e.response.text[:200]}"}
        except Exception as e:
            return {"error": str(e)}
