"""Wire all built-in MCP server wrappers into the MCP catalog."""
from __future__ import annotations

from typing import Any


def get_builtin_server_configs() -> list[dict]:
    """Return configurations for all built-in MCP server wrappers."""
    from app.mcp.servers import (
        # Original
        github_server,
        postgres_server,
        slack_server,
        # CRM & Sales
        hubspot_server,
        salesforce_server,
        pipedrive_server,
        close_crm_server,
        zoho_crm_server,
        copper_server,
        affinity_server,
        apollo_server,
        attio_server,
        # Project Management & Dev
        jira_server,
        confluence_server,
        linear_server,
        asana_server,
        bitbucket_server,
        gitlab_server,
        jenkins_server,
        trello_server,
        monday_server,
        todoist_server,
        basecamp_server,
        wrike_server,
        clickup_server,
        smartsuite_server,
        # Additional CRM
        linkedin_ads_server,
        planhat_server,
        # Google Workspace
        google_drive_server,
        google_calendar_server,
        google_analytics_server,
        google_ads_server,
        google_search_console_server,
        google_cloud_storage_server,
        # Payments & Finance
        stripe_server,
        paypal_server,
        square_server,
        razorpay_server,
        quickbooks_server,
        # File Storage
        dropbox_server,
        box_server,
        microsoft_onedrive_server,
        # Communication
        discord_server,
        telegram_server,
        whatsapp_server,
        microsoft_teams_server,
        mattermost_server,
        # Data & Analytics
        mongodb_server,
        mysql_server,
        redis_server,
        snowflake_server,
        # Marketing & Email
        sendgrid_server,
        mailchimp_server,
        klaviyo_server,
        brevo_server,
        mailerlite_server,
        convertkit_server,
        customerio_server,
        twilio_server,
        mandrill_server,
        # Business Intelligence
        gong_server,
        intercom_server,
        linkedin_server,
        google_docs_server,
        google_sheets_server,
        # HR & Workforce (new)
        bamboohr_server,
        workday_server,
        deel_server,
        rippling_server,
        # Customer Support (new)
        zendesk_server,
        freshdesk_server,
        freshservice_server,
        gorgias_server,
        front_server,
        # E-commerce & Social (new)
        shopify_server,
        wordpress_server,
        webflow_server,
        woocommerce_server,
        x_twitter_server,
        instagram_server,
        tiktok_server,
        youtube_server,
        # AI & Search (new)
        openai_server,
        perplexity_server,
        tavily_server,
        serpapi_server,
        brave_search_server,
        firecrawl_server,
        # Communication & Scheduling (new)
        zoom_server,
        calendly_server,
        docusign_server,
        pandadoc_server,
         # Finance & Accounting (new)
        xero_server,
        chargebee_server,
        # Developer Tools (new)
        notion_server,
        postman_server,
        # ── Project Management (additional) ──────────────────────────────────
        trello_server,
        monday_server,
        todoist_server,
        basecamp_server,
        wrike_server,
        clickup_server,
        # ── Cloud Storage & Files ─────────────────────────────────────────────
        dropbox_server,
        google_drive_server,
        google_calendar_server,
        # ── Payments ─────────────────────────────────────────────────────────
        stripe_server,
        # ── Databases, Analytics & Monitoring (new) ──────────────────────────
        elasticsearch_server,
        supabase_server,
        pinecone_server,
        sentry_server,
        new_relic_server,
        mixpanel_server,
        amplitude_server,
        prometheus_server,
        splunk_server,
        loggly_server,
        # ── CRM additions ────────────────────────────────────────────────────
        linkedin_ads_server,
        planhat_server,
        # ── Project Management (remaining) ───────────────────────────────────
        trello_server,
        monday_server,
        todoist_server,
        basecamp_server,
        wrike_server,
        clickup_server,
        smartsuite_server,
        # ── Google Workspace & Cloud (new) ────────────────────────────────────
        google_drive_server,
        google_calendar_server,
        google_analytics_server,
        google_ads_server,
        google_search_console_server,
        google_cloud_storage_server,
        # ── Payments (new) ────────────────────────────────────────────────────
        stripe_server,
        paypal_server,
        square_server,
        razorpay_server,
        quickbooks_server,
        # ── Cloud File Storage (new) ──────────────────────────────────────────
        dropbox_server,
        box_server,
        microsoft_onedrive_server,
        # ── AWS ───────────────────────────────────────────────────────────────
        aws_cloudwatch_server,
        aws_iam_server,
        aws_lambda_server,
        aws_s3_server,
        # ── Azure DevOps ──────────────────────────────────────────────────────
        azure_devops_server,
        # ── Cloud & Infrastructure ────────────────────────────────────────────
        digitalocean_server,
        docker_server,
        heroku_server,
        kubernetes_server,
        netlify_server,
        vercel_server,
    )

    raw_configs = [
        # ── Original ──────────────────────────────────────────────────────────
        {
            "server_id": "builtin-github",
            "name": "GitHub",
            "description": "GitHub repositories, issues, PRs, and code search",
            "tool_definitions": github_server.TOOL_DEFINITIONS,
            "handler": github_server.call_tool,
            "requires_env": ["GITHUB_TOKEN"],
        },
        {
            "server_id": "builtin-postgres",
            "name": "PostgreSQL",
            "description": "Query PostgreSQL databases",
            "tool_definitions": postgres_server.TOOL_DEFINITIONS,
            "handler": postgres_server.call_tool,
            "requires_env": ["POSTGRES_MCP_URL"],
        },
        {
            "server_id": "builtin-slack",
            "name": "Slack",
            "description": "Send messages and search Slack",
            "tool_definitions": slack_server.TOOL_DEFINITIONS,
            "handler": slack_server.call_tool,
            "requires_env": ["SLACK_BOT_TOKEN"],
        },
        # ── CRM & Sales ───────────────────────────────────────────────────────
        {
            "server_id": "builtin-hubspot",
            "name": "HubSpot",
            "description": "HubSpot CRM contacts, deals, companies, and notes",
            "tool_definitions": hubspot_server.TOOL_DEFINITIONS,
            "handler": hubspot_server.call_tool,
            "requires_env": ["HUBSPOT_API_KEY"],
        },
        {
            "server_id": "builtin-salesforce",
            "name": "Salesforce",
            "description": "Salesforce CRM objects, queries, and workflows",
            "tool_definitions": salesforce_server.TOOL_DEFINITIONS,
            "handler": salesforce_server.call_tool,
            "requires_env": ["SALESFORCE_INSTANCE_URL", "SALESFORCE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-pipedrive",
            "name": "Pipedrive",
            "description": "Pipedrive CRM deals, persons, and activities",
            "tool_definitions": pipedrive_server.TOOL_DEFINITIONS,
            "handler": pipedrive_server.call_tool,
            "requires_env": ["PIPEDRIVE_API_TOKEN"],
        },
        {
            "server_id": "builtin-close-crm",
            "name": "Close CRM",
            "description": "Close CRM leads, contacts, and opportunities",
            "tool_definitions": close_crm_server.TOOL_DEFINITIONS,
            "handler": close_crm_server.call_tool,
            "requires_env": ["CLOSE_API_KEY"],
        },
        {
            "server_id": "builtin-zoho-crm",
            "name": "Zoho CRM",
            "description": "Zoho CRM leads, contacts, and deals",
            "tool_definitions": zoho_crm_server.TOOL_DEFINITIONS,
            "handler": zoho_crm_server.call_tool,
            "requires_env": ["ZOHO_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-copper",
            "name": "Copper CRM",
            "description": "Copper CRM people, companies, and opportunities",
            "tool_definitions": copper_server.TOOL_DEFINITIONS,
            "handler": copper_server.call_tool,
            "requires_env": ["COPPER_API_KEY", "COPPER_USER_EMAIL"],
        },
        {
            "server_id": "builtin-affinity",
            "name": "Affinity",
            "description": "Affinity relationship intelligence CRM",
            "tool_definitions": affinity_server.TOOL_DEFINITIONS,
            "handler": affinity_server.call_tool,
            "requires_env": ["AFFINITY_API_KEY"],
        },
        {
            "server_id": "builtin-apollo",
            "name": "Apollo.io",
            "description": "Apollo.io sales intelligence and prospecting",
            "tool_definitions": apollo_server.TOOL_DEFINITIONS,
            "handler": apollo_server.call_tool,
            "requires_env": ["APOLLO_API_KEY"],
        },
        {
            "server_id": "builtin-attio",
            "name": "Attio",
            "description": "Attio CRM records and workspaces",
            "tool_definitions": attio_server.TOOL_DEFINITIONS,
            "handler": attio_server.call_tool,
            "requires_env": ["ATTIO_API_KEY"],
        },
        # ── Project Management & Dev ──────────────────────────────────────────
        {
            "server_id": "builtin-jira",
            "name": "Jira",
            "description": "Jira issues, projects, and sprints",
            "tool_definitions": jira_server.TOOL_DEFINITIONS,
            "handler": jira_server.call_tool,
            "requires_env": ["JIRA_BASE_URL", "JIRA_EMAIL", "JIRA_API_TOKEN"],
        },
        {
            "server_id": "builtin-confluence",
            "name": "Confluence",
            "description": "Confluence pages and spaces",
            "tool_definitions": confluence_server.TOOL_DEFINITIONS,
            "handler": confluence_server.call_tool,
            "requires_env": ["CONFLUENCE_BASE_URL", "CONFLUENCE_EMAIL", "CONFLUENCE_API_TOKEN"],
        },
        {
            "server_id": "builtin-linear",
            "name": "Linear",
            "description": "Linear issues, cycles, and projects",
            "tool_definitions": linear_server.TOOL_DEFINITIONS,
            "handler": linear_server.call_tool,
            "requires_env": ["LINEAR_API_KEY"],
        },
        {
            "server_id": "builtin-asana",
            "name": "Asana",
            "description": "Asana tasks, projects, and workspaces",
            "tool_definitions": asana_server.TOOL_DEFINITIONS,
            "handler": asana_server.call_tool,
            "requires_env": ["ASANA_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-bitbucket",
            "name": "Bitbucket",
            "description": "Bitbucket repositories, PRs, and pipelines",
            "tool_definitions": bitbucket_server.TOOL_DEFINITIONS,
            "handler": bitbucket_server.call_tool,
            "requires_env": ["BITBUCKET_USERNAME", "BITBUCKET_APP_PASSWORD"],
        },
        {
            "server_id": "builtin-gitlab",
            "name": "GitLab",
            "description": "GitLab repositories, MRs, and CI/CD",
            "tool_definitions": gitlab_server.TOOL_DEFINITIONS,
            "handler": gitlab_server.call_tool,
            "requires_env": ["GITLAB_TOKEN"],
        },
        {
            "server_id": "builtin-jenkins",
            "name": "Jenkins",
            "description": "Jenkins CI/CD jobs and build management",
            "tool_definitions": jenkins_server.TOOL_DEFINITIONS,
            "handler": jenkins_server.call_tool,
            "requires_env": ["JENKINS_URL", "JENKINS_USER", "JENKINS_API_TOKEN"],
        },
        {
            "server_id": "builtin-trello",
            "name": "Trello",
            "description": "Trello boards, lists, and cards",
            "tool_definitions": trello_server.TOOL_DEFINITIONS,
            "handler": trello_server.call_tool,
            "requires_env": ["TRELLO_API_KEY", "TRELLO_TOKEN"],
        },
        {
            "server_id": "builtin-monday",
            "name": "Monday.com",
            "description": "Monday.com boards and items",
            "tool_definitions": monday_server.TOOL_DEFINITIONS,
            "handler": monday_server.call_tool,
            "requires_env": ["MONDAY_API_KEY"],
        },
        {
            "server_id": "builtin-todoist",
            "name": "Todoist",
            "description": "Todoist tasks and projects",
            "tool_definitions": todoist_server.TOOL_DEFINITIONS,
            "handler": todoist_server.call_tool,
            "requires_env": ["TODOIST_API_TOKEN"],
        },
        {
            "server_id": "builtin-basecamp",
            "name": "Basecamp",
            "description": "Basecamp projects, todos, and messages",
            "tool_definitions": basecamp_server.TOOL_DEFINITIONS,
            "handler": basecamp_server.call_tool,
            "requires_env": ["BASECAMP_ACCESS_TOKEN", "BASECAMP_ACCOUNT_ID"],
        },
        {
            "server_id": "builtin-wrike",
            "name": "Wrike",
            "description": "Wrike tasks, folders, and projects",
            "tool_definitions": wrike_server.TOOL_DEFINITIONS,
            "handler": wrike_server.call_tool,
            "requires_env": ["WRIKE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-clickup",
            "name": "ClickUp",
            "description": "ClickUp tasks, spaces, and workspaces",
            "tool_definitions": clickup_server.TOOL_DEFINITIONS,
            "handler": clickup_server.call_tool,
            "requires_env": ["CLICKUP_API_TOKEN"],
        },
        {
            "server_id": "builtin-smartsuite",
            "name": "SmartSuite",
            "description": "SmartSuite records and solutions",
            "tool_definitions": smartsuite_server.TOOL_DEFINITIONS,
            "handler": smartsuite_server.call_tool,
            "requires_env": ["SMARTSUITE_API_KEY", "SMARTSUITE_ACCOUNT_ID"],
        },
        # ── Additional CRM ────────────────────────────────────────────────────
        {
            "server_id": "builtin-linkedin-ads",
            "name": "LinkedIn Ads",
            "description": "LinkedIn Ads campaigns and analytics",
            "tool_definitions": linkedin_ads_server.TOOL_DEFINITIONS,
            "handler": linkedin_ads_server.call_tool,
            "requires_env": ["LINKEDIN_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-planhat",
            "name": "Planhat",
            "description": "Planhat customer success and health scores",
            "tool_definitions": planhat_server.TOOL_DEFINITIONS,
            "handler": planhat_server.call_tool,
            "requires_env": ["PLANHAT_API_KEY"],
        },
        # ── Google Workspace ──────────────────────────────────────────────────
        {
            "server_id": "builtin-google-drive",
            "name": "Google Drive",
            "description": "Google Drive file management",
            "tool_definitions": google_drive_server.TOOL_DEFINITIONS,
            "handler": google_drive_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-google-calendar",
            "name": "Google Calendar",
            "description": "Google Calendar events and scheduling",
            "tool_definitions": google_calendar_server.TOOL_DEFINITIONS,
            "handler": google_calendar_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-google-analytics",
            "name": "Google Analytics",
            "description": "Google Analytics GA4 reporting",
            "tool_definitions": google_analytics_server.TOOL_DEFINITIONS,
            "handler": google_analytics_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-google-ads",
            "name": "Google Ads",
            "description": "Google Ads campaigns and performance",
            "tool_definitions": google_ads_server.TOOL_DEFINITIONS,
            "handler": google_ads_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN", "GOOGLE_ADS_DEVELOPER_TOKEN"],
        },
        {
            "server_id": "builtin-google-search-console",
            "name": "Google Search Console",
            "description": "Google Search Console performance and indexing",
            "tool_definitions": google_search_console_server.TOOL_DEFINITIONS,
            "handler": google_search_console_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-google-cloud-storage",
            "name": "Google Cloud Storage",
            "description": "Google Cloud Storage buckets and objects",
            "tool_definitions": google_cloud_storage_server.TOOL_DEFINITIONS,
            "handler": google_cloud_storage_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        # ── Payments & Finance ────────────────────────────────────────────────
        {
            "server_id": "builtin-stripe",
            "name": "Stripe",
            "description": "Stripe payments, customers, and subscriptions",
            "tool_definitions": stripe_server.TOOL_DEFINITIONS,
            "handler": stripe_server.call_tool,
            "requires_env": ["STRIPE_SECRET_KEY"],
        },
        {
            "server_id": "builtin-paypal",
            "name": "PayPal",
            "description": "PayPal payments, orders, and invoicing",
            "tool_definitions": paypal_server.TOOL_DEFINITIONS,
            "handler": paypal_server.call_tool,
            "requires_env": ["PAYPAL_CLIENT_ID", "PAYPAL_CLIENT_SECRET"],
        },
        {
            "server_id": "builtin-square",
            "name": "Square",
            "description": "Square payments, catalog, and orders",
            "tool_definitions": square_server.TOOL_DEFINITIONS,
            "handler": square_server.call_tool,
            "requires_env": ["SQUARE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-razorpay",
            "name": "Razorpay",
            "description": "Razorpay payments and orders",
            "tool_definitions": razorpay_server.TOOL_DEFINITIONS,
            "handler": razorpay_server.call_tool,
            "requires_env": ["RAZORPAY_KEY_ID", "RAZORPAY_KEY_SECRET"],
        },
        {
            "server_id": "builtin-quickbooks",
            "name": "QuickBooks",
            "description": "QuickBooks accounting and invoicing",
            "tool_definitions": quickbooks_server.TOOL_DEFINITIONS,
            "handler": quickbooks_server.call_tool,
            "requires_env": ["QUICKBOOKS_ACCESS_TOKEN", "QUICKBOOKS_COMPANY_ID"],
        },
        # ── File Storage ──────────────────────────────────────────────────────
        {
            "server_id": "builtin-dropbox",
            "name": "Dropbox",
            "description": "Dropbox file management",
            "tool_definitions": dropbox_server.TOOL_DEFINITIONS,
            "handler": dropbox_server.call_tool,
            "requires_env": ["DROPBOX_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-box",
            "name": "Box",
            "description": "Box content management and collaboration",
            "tool_definitions": box_server.TOOL_DEFINITIONS,
            "handler": box_server.call_tool,
            "requires_env": ["BOX_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-onedrive",
            "name": "Microsoft OneDrive",
            "description": "Microsoft OneDrive file storage",
            "tool_definitions": microsoft_onedrive_server.TOOL_DEFINITIONS,
            "handler": microsoft_onedrive_server.call_tool,
            "requires_env": ["ONEDRIVE_ACCESS_TOKEN"],
        },
        # ── Communication ─────────────────────────────────────────────────────
        {
            "server_id": "builtin-discord",
            "name": "Discord",
            "description": "Discord messages, channels, and server management",
            "tool_definitions": discord_server.TOOL_DEFINITIONS,
            "handler": discord_server.call_tool,
            "requires_env": ["DISCORD_BOT_TOKEN"],
        },
        {
            "server_id": "builtin-telegram",
            "name": "Telegram",
            "description": "Telegram bot messages and channels",
            "tool_definitions": telegram_server.TOOL_DEFINITIONS,
            "handler": telegram_server.call_tool,
            "requires_env": ["TELEGRAM_BOT_TOKEN"],
        },
        {
            "server_id": "builtin-whatsapp",
            "name": "WhatsApp",
            "description": "WhatsApp Business API messages",
            "tool_definitions": whatsapp_server.TOOL_DEFINITIONS,
            "handler": whatsapp_server.call_tool,
            "requires_env": ["WHATSAPP_ACCESS_TOKEN", "WHATSAPP_PHONE_NUMBER_ID"],
        },
        {
            "server_id": "builtin-microsoft-teams",
            "name": "Microsoft Teams",
            "description": "Microsoft Teams messages and channels",
            "tool_definitions": microsoft_teams_server.TOOL_DEFINITIONS,
            "handler": microsoft_teams_server.call_tool,
            "requires_env": ["TEAMS_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-mattermost",
            "name": "Mattermost",
            "description": "Mattermost messages and channels",
            "tool_definitions": mattermost_server.TOOL_DEFINITIONS,
            "handler": mattermost_server.call_tool,
            "requires_env": ["MATTERMOST_URL", "MATTERMOST_TOKEN"],
        },
        # ── Data & Analytics ──────────────────────────────────────────────────
        {
            "server_id": "builtin-mongodb",
            "name": "MongoDB",
            "description": "MongoDB collections and queries",
            "tool_definitions": mongodb_server.TOOL_DEFINITIONS,
            "handler": mongodb_server.call_tool,
            "requires_env": ["MONGODB_MCP_URL"],
        },
        {
            "server_id": "builtin-mysql",
            "name": "MySQL",
            "description": "MySQL database queries",
            "tool_definitions": mysql_server.TOOL_DEFINITIONS,
            "handler": mysql_server.call_tool,
            "requires_env": ["MYSQL_MCP_URL"],
        },
        {
            "server_id": "builtin-redis",
            "name": "Redis",
            "description": "Redis key-value store operations",
            "tool_definitions": redis_server.TOOL_DEFINITIONS,
            "handler": redis_server.call_tool,
            "requires_env": ["REDIS_MCP_URL"],
        },
        {
            "server_id": "builtin-snowflake",
            "name": "Snowflake",
            "description": "Snowflake data warehouse queries",
            "tool_definitions": snowflake_server.TOOL_DEFINITIONS,
            "handler": snowflake_server.call_tool,
            "requires_env": ["SNOWFLAKE_ACCOUNT", "SNOWFLAKE_USER", "SNOWFLAKE_PASSWORD"],
        },
        # ── Marketing & Email ─────────────────────────────────────────────────
        {
            "server_id": "builtin-sendgrid",
            "name": "SendGrid",
            "description": "SendGrid email sending and marketing",
            "tool_definitions": sendgrid_server.TOOL_DEFINITIONS,
            "handler": sendgrid_server.call_tool,
            "requires_env": ["SENDGRID_API_KEY"],
        },
        {
            "server_id": "builtin-mailchimp",
            "name": "Mailchimp",
            "description": "Mailchimp email campaigns and audiences",
            "tool_definitions": mailchimp_server.TOOL_DEFINITIONS,
            "handler": mailchimp_server.call_tool,
            "requires_env": ["MAILCHIMP_API_KEY"],
        },
        # ── Business Intelligence ─────────────────────────────────────────────
        {
            "server_id": "builtin-gong",
            "name": "Gong",
            "description": "Gong revenue intelligence and call analytics",
            "tool_definitions": gong_server.TOOL_DEFINITIONS,
            "handler": gong_server.call_tool,
            "requires_env": ["GONG_ACCESS_KEY", "GONG_ACCESS_KEY_SECRET"],
        },
        {
            "server_id": "builtin-intercom",
            "name": "Intercom",
            "description": "Intercom customer messaging and support",
            "tool_definitions": intercom_server.TOOL_DEFINITIONS,
            "handler": intercom_server.call_tool,
            "requires_env": ["INTERCOM_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-linkedin",
            "name": "LinkedIn",
            "description": "LinkedIn profiles and company data",
            "tool_definitions": linkedin_server.TOOL_DEFINITIONS,
            "handler": linkedin_server.call_tool,
            "requires_env": ["LINKEDIN_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-linkedin-ads",
            "name": "LinkedIn Ads",
            "description": "LinkedIn Ads — ad accounts, campaigns, creatives, and analytics",
            "tool_definitions": linkedin_ads_server.TOOL_DEFINITIONS,
            "handler": linkedin_ads_server.call_tool,
            "requires_env": ["LINKEDIN_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-planhat",
            "name": "Planhat",
            "description": "Planhat customer success — companies, end-users, and activity logging",
            "tool_definitions": planhat_server.TOOL_DEFINITIONS,
            "handler": planhat_server.call_tool,
            "requires_env": ["PLANHAT_API_KEY"],
        },
        {
            "server_id": "builtin-google-docs",
            "name": "Google Docs",
            "description": "Google Docs document creation and management",
            "tool_definitions": google_docs_server.TOOL_DEFINITIONS,
            "handler": google_docs_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-google-sheets",
            "name": "Google Sheets",
            "description": "Google Sheets spreadsheet operations",
            "tool_definitions": google_sheets_server.TOOL_DEFINITIONS,
            "handler": google_sheets_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        # ── HR & Workforce ────────────────────────────────────────────────────
        {
            "server_id": "builtin-bamboohr",
            "name": "BambooHR",
            "description": "BambooHR employee data, time-off, and HR management",
            "tool_definitions": bamboohr_server.TOOL_DEFINITIONS,
            "handler": bamboohr_server.call_tool,
            "requires_env": ["BAMBOOHR_API_KEY", "BAMBOOHR_SUBDOMAIN"],
        },
        {
            "server_id": "builtin-workday",
            "name": "Workday",
            "description": "Workday HR and workforce management",
            "tool_definitions": workday_server.TOOL_DEFINITIONS,
            "handler": workday_server.call_tool,
            "requires_env": ["WORKDAY_CLIENT_ID", "WORKDAY_CLIENT_SECRET", "WORKDAY_TENANT", "WORKDAY_BASE_URL"],
        },
        {
            "server_id": "builtin-deel",
            "name": "Deel",
            "description": "Deel global payroll, contracts, and compliance",
            "tool_definitions": deel_server.TOOL_DEFINITIONS,
            "handler": deel_server.call_tool,
            "requires_env": ["DEEL_API_KEY"],
        },
        {
            "server_id": "builtin-rippling",
            "name": "Rippling",
            "description": "Rippling HR, IT, and payroll platform",
            "tool_definitions": rippling_server.TOOL_DEFINITIONS,
            "handler": rippling_server.call_tool,
            "requires_env": ["RIPPLING_API_KEY"],
        },
        # ── Customer Support ──────────────────────────────────────────────────
        {
            "server_id": "builtin-zendesk",
            "name": "Zendesk",
            "description": "Zendesk support tickets, users, and organizations",
            "tool_definitions": zendesk_server.TOOL_DEFINITIONS,
            "handler": zendesk_server.call_tool,
            "requires_env": ["ZENDESK_SUBDOMAIN", "ZENDESK_EMAIL", "ZENDESK_API_TOKEN"],
        },
        {
            "server_id": "builtin-freshdesk",
            "name": "Freshdesk",
            "description": "Freshdesk customer support tickets and contacts",
            "tool_definitions": freshdesk_server.TOOL_DEFINITIONS,
            "handler": freshdesk_server.call_tool,
            "requires_env": ["FRESHDESK_DOMAIN", "FRESHDESK_API_KEY"],
        },
        {
            "server_id": "builtin-freshservice",
            "name": "Freshservice",
            "description": "Freshservice IT service management",
            "tool_definitions": freshservice_server.TOOL_DEFINITIONS,
            "handler": freshservice_server.call_tool,
            "requires_env": ["FRESHSERVICE_DOMAIN", "FRESHSERVICE_API_KEY"],
        },
        {
            "server_id": "builtin-gorgias",
            "name": "Gorgias",
            "description": "Gorgias e-commerce customer support platform",
            "tool_definitions": gorgias_server.TOOL_DEFINITIONS,
            "handler": gorgias_server.call_tool,
            "requires_env": ["GORGIAS_DOMAIN", "GORGIAS_EMAIL", "GORGIAS_API_KEY"],
        },
        {
            "server_id": "builtin-front",
            "name": "Front",
            "description": "Front shared inbox and customer communication",
            "tool_definitions": front_server.TOOL_DEFINITIONS,
            "handler": front_server.call_tool,
            "requires_env": ["FRONT_API_TOKEN"],
        },
        # ── E-commerce ────────────────────────────────────────────────────────
        {
            "server_id": "builtin-shopify",
            "name": "Shopify",
            "description": "Shopify products, orders, customers, and inventory",
            "tool_definitions": shopify_server.TOOL_DEFINITIONS,
            "handler": shopify_server.call_tool,
            "requires_env": ["SHOPIFY_STORE_URL", "SHOPIFY_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-wordpress",
            "name": "WordPress",
            "description": "WordPress posts, pages, and content management",
            "tool_definitions": wordpress_server.TOOL_DEFINITIONS,
            "handler": wordpress_server.call_tool,
            "requires_env": ["WORDPRESS_URL", "WORDPRESS_USERNAME", "WORDPRESS_APP_PASSWORD"],
        },
        {
            "server_id": "builtin-webflow",
            "name": "Webflow",
            "description": "Webflow CMS collections, sites, and publishing",
            "tool_definitions": webflow_server.TOOL_DEFINITIONS,
            "handler": webflow_server.call_tool,
            "requires_env": ["WEBFLOW_API_TOKEN"],
        },
        {
            "server_id": "builtin-woocommerce",
            "name": "WooCommerce",
            "description": "WooCommerce products, orders, and customers",
            "tool_definitions": woocommerce_server.TOOL_DEFINITIONS,
            "handler": woocommerce_server.call_tool,
            "requires_env": ["WOOCOMMERCE_URL", "WOOCOMMERCE_CONSUMER_KEY", "WOOCOMMERCE_CONSUMER_SECRET"],
        },
        # ── Social Media ──────────────────────────────────────────────────────
        {
            "server_id": "builtin-x-twitter",
            "name": "X (Twitter)",
            "description": "X/Twitter tweets, users, and search",
            "tool_definitions": x_twitter_server.TOOL_DEFINITIONS,
            "handler": x_twitter_server.call_tool,
            "requires_env": ["TWITTER_BEARER_TOKEN"],
        },
        {
            "server_id": "builtin-instagram",
            "name": "Instagram",
            "description": "Instagram Business account management and insights",
            "tool_definitions": instagram_server.TOOL_DEFINITIONS,
            "handler": instagram_server.call_tool,
            "requires_env": ["INSTAGRAM_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-tiktok",
            "name": "TikTok",
            "description": "TikTok Business API for videos, insights, and campaigns",
            "tool_definitions": tiktok_server.TOOL_DEFINITIONS,
            "handler": tiktok_server.call_tool,
            "requires_env": ["TIKTOK_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-youtube",
            "name": "YouTube",
            "description": "YouTube videos, channels, playlists, and comments",
            "tool_definitions": youtube_server.TOOL_DEFINITIONS,
            "handler": youtube_server.call_tool,
            "requires_env": ["YOUTUBE_API_KEY"],
        },
        # ── AI & Search ───────────────────────────────────────────────────────
        {
            "server_id": "builtin-openai",
            "name": "OpenAI",
            "description": "OpenAI chat completions, embeddings, images, TTS, and assistants",
            "tool_definitions": openai_server.TOOL_DEFINITIONS,
            "handler": openai_server.call_tool,
            "requires_env": ["OPENAI_API_KEY"],
        },
        {
            "server_id": "builtin-perplexity",
            "name": "Perplexity",
            "description": "Perplexity AI-powered web search and research",
            "tool_definitions": perplexity_server.TOOL_DEFINITIONS,
            "handler": perplexity_server.call_tool,
            "requires_env": ["PERPLEXITY_API_KEY"],
        },
        {
            "server_id": "builtin-tavily",
            "name": "Tavily",
            "description": "Tavily AI-optimized web search and content extraction",
            "tool_definitions": tavily_server.TOOL_DEFINITIONS,
            "handler": tavily_server.call_tool,
            "requires_env": ["TAVILY_API_KEY"],
        },
        {
            "server_id": "builtin-serpapi",
            "name": "SerpAPI",
            "description": "SerpAPI Google Search, News, Images, and Shopping",
            "tool_definitions": serpapi_server.TOOL_DEFINITIONS,
            "handler": serpapi_server.call_tool,
            "requires_env": ["SERPAPI_API_KEY"],
        },
        {
            "server_id": "builtin-brave-search",
            "name": "Brave Search",
            "description": "Brave privacy-focused web and news search",
            "tool_definitions": brave_search_server.TOOL_DEFINITIONS,
            "handler": brave_search_server.call_tool,
            "requires_env": ["BRAVE_SEARCH_API_KEY"],
        },
        {
            "server_id": "builtin-firecrawl",
            "name": "Firecrawl",
            "description": "Firecrawl web scraping, crawling, and URL mapping",
            "tool_definitions": firecrawl_server.TOOL_DEFINITIONS,
            "handler": firecrawl_server.call_tool,
            "requires_env": ["FIRECRAWL_API_KEY"],
        },
        # ── Communication & Scheduling ────────────────────────────────────────
        {
            "server_id": "builtin-zoom",
            "name": "Zoom",
            "description": "Zoom meetings, recordings, and user management",
            "tool_definitions": zoom_server.TOOL_DEFINITIONS,
            "handler": zoom_server.call_tool,
            "requires_env": ["ZOOM_OAUTH_TOKEN"],
        },
        {
            "server_id": "builtin-calendly",
            "name": "Calendly",
            "description": "Calendly scheduling, event types, and invitations",
            "tool_definitions": calendly_server.TOOL_DEFINITIONS,
            "handler": calendly_server.call_tool,
            "requires_env": ["CALENDLY_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-docusign",
            "name": "DocuSign",
            "description": "DocuSign eSignature envelopes and signing workflows",
            "tool_definitions": docusign_server.TOOL_DEFINITIONS,
            "handler": docusign_server.call_tool,
            "requires_env": ["DOCUSIGN_ACCESS_TOKEN", "DOCUSIGN_ACCOUNT_ID"],
        },
        {
            "server_id": "builtin-pandadoc",
            "name": "PandaDoc",
            "description": "PandaDoc document creation, templates, and eSignature",
            "tool_definitions": pandadoc_server.TOOL_DEFINITIONS,
            "handler": pandadoc_server.call_tool,
            "requires_env": ["PANDADOC_API_KEY"],
        },
        # ── Finance & Accounting ──────────────────────────────────────────────
        {
            "server_id": "builtin-xero",
            "name": "Xero",
            "description": "Xero accounting, invoices, and contacts",
            "tool_definitions": xero_server.TOOL_DEFINITIONS,
            "handler": xero_server.call_tool,
            "requires_env": ["XERO_ACCESS_TOKEN", "XERO_TENANT_ID"],
        },
        {
            "server_id": "builtin-chargebee",
            "name": "Chargebee",
            "description": "Chargebee subscription billing and customer management",
            "tool_definitions": chargebee_server.TOOL_DEFINITIONS,
            "handler": chargebee_server.call_tool,
            "requires_env": ["CHARGEBEE_SITE", "CHARGEBEE_API_KEY"],
        },
        # ── Developer Tools ───────────────────────────────────────────────────
        {
            "server_id": "builtin-notion",
            "name": "Notion",
            "description": "Notion pages, databases, blocks, and search",
            "tool_definitions": notion_server.TOOL_DEFINITIONS,
            "handler": notion_server.call_tool,
            "requires_env": ["NOTION_API_KEY"],
        },
        {
            "server_id": "builtin-postman",
            "name": "Postman",
            "description": "Postman collections, environments, and API management",
            "tool_definitions": postman_server.TOOL_DEFINITIONS,
            "handler": postman_server.call_tool,
            "requires_env": ["POSTMAN_API_KEY"],
        },
        # ── Project Management (additional) ──────────────────────────────────
        {
            "server_id": "builtin-trello",
            "name": "Trello",
            "description": "Trello boards, lists, and card management",
            "tool_definitions": trello_server.TOOL_DEFINITIONS,
            "handler": trello_server.call_tool,
            "requires_env": ["TRELLO_API_KEY", "TRELLO_TOKEN"],
        },
        {
            "server_id": "builtin-monday",
            "name": "Monday.com",
            "description": "Monday.com boards, items, and columns",
            "tool_definitions": monday_server.TOOL_DEFINITIONS,
            "handler": monday_server.call_tool,
            "requires_env": ["MONDAY_API_KEY"],
        },
        {
            "server_id": "builtin-todoist",
            "name": "Todoist",
            "description": "Todoist tasks, projects, and productivity",
            "tool_definitions": todoist_server.TOOL_DEFINITIONS,
            "handler": todoist_server.call_tool,
            "requires_env": ["TODOIST_API_TOKEN"],
        },
        {
            "server_id": "builtin-basecamp",
            "name": "Basecamp",
            "description": "Basecamp projects, messages, and to-dos",
            "tool_definitions": basecamp_server.TOOL_DEFINITIONS,
            "handler": basecamp_server.call_tool,
            "requires_env": ["BASECAMP_ACCESS_TOKEN", "BASECAMP_ACCOUNT_ID"],
        },
        {
            "server_id": "builtin-wrike",
            "name": "Wrike",
            "description": "Wrike tasks, folders, and project management",
            "tool_definitions": wrike_server.TOOL_DEFINITIONS,
            "handler": wrike_server.call_tool,
            "requires_env": ["WRIKE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-clickup",
            "name": "ClickUp",
            "description": "ClickUp tasks, lists, spaces, and workspaces",
            "tool_definitions": clickup_server.TOOL_DEFINITIONS,
            "handler": clickup_server.call_tool,
            "requires_env": ["CLICKUP_API_KEY"],
        },
        # ── Cloud Storage & Files ─────────────────────────────────────────────
        {
            "server_id": "builtin-dropbox",
            "name": "Dropbox",
            "description": "Dropbox file and folder management",
            "tool_definitions": dropbox_server.TOOL_DEFINITIONS,
            "handler": dropbox_server.call_tool,
            "requires_env": ["DROPBOX_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-google-drive",
            "name": "Google Drive",
            "description": "Google Drive files, folders, and sharing",
            "tool_definitions": google_drive_server.TOOL_DEFINITIONS,
            "handler": google_drive_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-google-calendar",
            "name": "Google Calendar",
            "description": "Google Calendar events and scheduling",
            "tool_definitions": google_calendar_server.TOOL_DEFINITIONS,
            "handler": google_calendar_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        # ── Payments ─────────────────────────────────────────────────────────
        {
            "server_id": "builtin-stripe",
            "name": "Stripe",
            "description": "Stripe payments, customers, and subscriptions",
            "tool_definitions": stripe_server.TOOL_DEFINITIONS,
            "handler": stripe_server.call_tool,
            "requires_env": ["STRIPE_API_KEY"],
        },
        # ── Databases, Analytics & Monitoring ────────────────────────────────
        {
            "server_id": "builtin-elasticsearch",
            "name": "Elasticsearch",
            "description": "Search and manage Elasticsearch indices",
            "tool_definitions": elasticsearch_server.TOOL_DEFINITIONS,
            "handler": elasticsearch_server.call_tool,
            "requires_env": ["ELASTICSEARCH_URL"],
        },
        {
            "server_id": "builtin-supabase",
            "name": "Supabase",
            "description": "Query and manage Supabase tables and auth",
            "tool_definitions": supabase_server.TOOL_DEFINITIONS,
            "handler": supabase_server.call_tool,
            "requires_env": ["SUPABASE_URL", "SUPABASE_SERVICE_KEY"],
        },
        {
            "server_id": "builtin-pinecone",
            "name": "Pinecone",
            "description": "Vector search and upsert operations on Pinecone indexes",
            "tool_definitions": pinecone_server.TOOL_DEFINITIONS,
            "handler": pinecone_server.call_tool,
            "requires_env": ["PINECONE_API_KEY"],
        },
        {
            "server_id": "builtin-sentry",
            "name": "Sentry",
            "description": "Manage Sentry issues, events, and releases",
            "tool_definitions": sentry_server.TOOL_DEFINITIONS,
            "handler": sentry_server.call_tool,
            "requires_env": ["SENTRY_AUTH_TOKEN", "SENTRY_ORG_SLUG"],
        },
        {
            "server_id": "builtin-new-relic",
            "name": "New Relic",
            "description": "Query metrics, alerts, and APM data from New Relic",
            "tool_definitions": new_relic_server.TOOL_DEFINITIONS,
            "handler": new_relic_server.call_tool,
            "requires_env": ["NEW_RELIC_API_KEY"],
        },
        {
            "server_id": "builtin-mixpanel",
            "name": "Mixpanel",
            "description": "Query Mixpanel event data, funnels, retention, and user profiles",
            "tool_definitions": mixpanel_server.TOOL_DEFINITIONS,
            "handler": mixpanel_server.call_tool,
            "requires_env": [
                "MIXPANEL_SERVICE_ACCOUNT_USERNAME",
                "MIXPANEL_SERVICE_ACCOUNT_SECRET",
                "MIXPANEL_PROJECT_ID",
            ],
        },
        {
            "server_id": "builtin-amplitude",
            "name": "Amplitude",
            "description": "Query Amplitude events, cohorts, and user profiles",
            "tool_definitions": amplitude_server.TOOL_DEFINITIONS,
            "handler": amplitude_server.call_tool,
            "requires_env": ["AMPLITUDE_API_KEY", "AMPLITUDE_SECRET_KEY"],
        },
        {
            "server_id": "builtin-prometheus",
            "name": "Prometheus",
            "description": "Query Prometheus metrics, alerts, and targets via PromQL",
            "tool_definitions": prometheus_server.TOOL_DEFINITIONS,
            "handler": prometheus_server.call_tool,
            "requires_env": ["PROMETHEUS_URL"],
        },
        {
            "server_id": "builtin-splunk",
            "name": "Splunk",
            "description": "Search and analyze Splunk log events via SPL",
            "tool_definitions": splunk_server.TOOL_DEFINITIONS,
            "handler": splunk_server.call_tool,
            "requires_env": ["SPLUNK_URL"],
        },
        {
            "server_id": "builtin-loggly",
            "name": "Loggly",
            "description": "Search and retrieve Loggly log events",
            "tool_definitions": loggly_server.TOOL_DEFINITIONS,
            "handler": loggly_server.call_tool,
            "requires_env": ["LOGGLY_ACCOUNT", "LOGGLY_API_TOKEN"],
        },
        # ── Email & Marketing (continued) ──────────────────────────────────
        {
            "server_id": "builtin-klaviyo",
            "name": "Klaviyo",
            "description": "Klaviyo — profiles, lists, events, and campaigns",
            "tool_definitions": klaviyo_server.TOOL_DEFINITIONS,
            "handler": klaviyo_server.call_tool,
            "requires_env": ["KLAVIYO_API_KEY"],
        },
        {
            "server_id": "builtin-brevo",
            "name": "Brevo",
            "description": "Brevo (Sendinblue) — transactional email, contacts, and campaigns",
            "tool_definitions": brevo_server.TOOL_DEFINITIONS,
            "handler": brevo_server.call_tool,
            "requires_env": ["BREVO_API_KEY"],
        },
        {
            "server_id": "builtin-mailerlite",
            "name": "MailerLite",
            "description": "MailerLite — subscribers, groups, and email campaigns",
            "tool_definitions": mailerlite_server.TOOL_DEFINITIONS,
            "handler": mailerlite_server.call_tool,
            "requires_env": ["MAILERLITE_API_KEY"],
        },
        {
            "server_id": "builtin-convertkit",
            "name": "ConvertKit",
            "description": "ConvertKit — subscribers, forms, sequences, and tags",
            "tool_definitions": convertkit_server.TOOL_DEFINITIONS,
            "handler": convertkit_server.call_tool,
            "requires_env": ["CONVERTKIT_API_KEY"],
        },
        {
            "server_id": "builtin-customerio",
            "name": "Customer.io",
            "description": "Customer.io — customer profiles, event tracking, and transactional email",
            "tool_definitions": customerio_server.TOOL_DEFINITIONS,
            "handler": customerio_server.call_tool,
            "requires_env": ["CUSTOMERIO_SITE_ID", "CUSTOMERIO_API_KEY"],
        },
        {
            "server_id": "builtin-twilio",
            "name": "Twilio",
            "description": "Twilio — SMS, WhatsApp messages, voice calls, and phone number lookup",
            "tool_definitions": twilio_server.TOOL_DEFINITIONS,
            "handler": twilio_server.call_tool,
            "requires_env": ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN"],
        },
        {
            "server_id": "builtin-mandrill",
            "name": "Mandrill",
            "description": "Mandrill (Mailchimp Transactional) — send, template, and search transactional email",
            "tool_definitions": mandrill_server.TOOL_DEFINITIONS,
            "handler": mandrill_server.call_tool,
            "requires_env": ["MANDRILL_API_KEY"],
        },
        # ── Project Management (remaining) ───────────────────────────────────
        {
            "server_id": "builtin-trello",
            "name": "Trello",
            "description": "Trello boards, lists, cards, and checklists",
            "tool_definitions": trello_server.TOOL_DEFINITIONS,
            "handler": trello_server.call_tool,
            "requires_env": ["TRELLO_API_KEY", "TRELLO_TOKEN"],
        },
        {
            "server_id": "builtin-monday",
            "name": "Monday.com",
            "description": "Monday.com boards, items, and team updates",
            "tool_definitions": monday_server.TOOL_DEFINITIONS,
            "handler": monday_server.call_tool,
            "requires_env": ["MONDAY_API_KEY"],
        },
        {
            "server_id": "builtin-todoist",
            "name": "Todoist",
            "description": "Todoist tasks, projects, and productivity tracking",
            "tool_definitions": todoist_server.TOOL_DEFINITIONS,
            "handler": todoist_server.call_tool,
            "requires_env": ["TODOIST_API_TOKEN"],
        },
        {
            "server_id": "builtin-basecamp",
            "name": "Basecamp",
            "description": "Basecamp projects, to-dos, and team messaging",
            "tool_definitions": basecamp_server.TOOL_DEFINITIONS,
            "handler": basecamp_server.call_tool,
            "requires_env": ["BASECAMP_ACCOUNT_ID", "BASECAMP_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-wrike",
            "name": "Wrike",
            "description": "Wrike tasks, folders, spaces, and project management",
            "tool_definitions": wrike_server.TOOL_DEFINITIONS,
            "handler": wrike_server.call_tool,
            "requires_env": ["WRIKE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-clickup",
            "name": "ClickUp",
            "description": "ClickUp workspaces, spaces, lists, tasks, and comments",
            "tool_definitions": clickup_server.TOOL_DEFINITIONS,
            "handler": clickup_server.call_tool,
            "requires_env": ["CLICKUP_API_TOKEN"],
        },
        {
            "server_id": "builtin-mandrill",
            "name": "Mandrill",
            "description": "Mandrill (Mailchimp Transactional) — send, template, and search transactional email",
            "tool_definitions": mandrill_server.TOOL_DEFINITIONS,
            "handler": mandrill_server.call_tool,
            "requires_env": ["MANDRILL_API_KEY"],
        },
        # ── Google Workspace & Cloud ──────────────────────────────────────────
        {
            "server_id": "builtin-google-drive",
            "name": "Google Drive",
            "description": "File management in Google Drive",
            "tool_definitions": google_drive_server.TOOL_DEFINITIONS,
            "handler": google_drive_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-google-calendar",
            "name": "Google Calendar",
            "description": "Manage calendar events and check availability",
            "tool_definitions": google_calendar_server.TOOL_DEFINITIONS,
            "handler": google_calendar_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-google-analytics",
            "name": "Google Analytics (GA4)",
            "description": "Website analytics reports via Google Analytics 4",
            "tool_definitions": google_analytics_server.TOOL_DEFINITIONS,
            "handler": google_analytics_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-google-ads",
            "name": "Google Ads",
            "description": "Campaign management and performance reporting via Google Ads API",
            "tool_definitions": google_ads_server.TOOL_DEFINITIONS,
            "handler": google_ads_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN", "GOOGLE_ADS_DEVELOPER_TOKEN"],
        },
        {
            "server_id": "builtin-google-search-console",
            "name": "Google Search Console",
            "description": "Search performance data and sitemap management",
            "tool_definitions": google_search_console_server.TOOL_DEFINITIONS,
            "handler": google_search_console_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-google-cloud-storage",
            "name": "Google Cloud Storage",
            "description": "Bucket and object management in Google Cloud Storage",
            "tool_definitions": google_cloud_storage_server.TOOL_DEFINITIONS,
            "handler": google_cloud_storage_server.call_tool,
            "requires_env": ["GOOGLE_ACCESS_TOKEN"],
        },
        # ── Payments ─────────────────────────────────────────────────────────
        {
            "server_id": "builtin-stripe",
            "name": "Stripe",
            "description": "Payments, subscriptions, customers, and billing via Stripe",
            "tool_definitions": stripe_server.TOOL_DEFINITIONS,
            "handler": stripe_server.call_tool,
            "requires_env": ["STRIPE_SECRET_KEY"],
        },
        {
            "server_id": "builtin-paypal",
            "name": "PayPal",
            "description": "PayPal orders, payouts, and transaction reporting",
            "tool_definitions": paypal_server.TOOL_DEFINITIONS,
            "handler": paypal_server.call_tool,
            "requires_env": ["PAYPAL_CLIENT_ID", "PAYPAL_CLIENT_SECRET"],
        },
        {
            "server_id": "builtin-square",
            "name": "Square",
            "description": "Square payments, customers, catalog, and orders",
            "tool_definitions": square_server.TOOL_DEFINITIONS,
            "handler": square_server.call_tool,
            "requires_env": ["SQUARE_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-razorpay",
            "name": "Razorpay",
            "description": "Razorpay payments, orders, refunds, and payouts",
            "tool_definitions": razorpay_server.TOOL_DEFINITIONS,
            "handler": razorpay_server.call_tool,
            "requires_env": ["RAZORPAY_KEY_ID", "RAZORPAY_KEY_SECRET"],
        },
        {
            "server_id": "builtin-quickbooks",
            "name": "QuickBooks Online",
            "description": "Accounting, invoices, customers, and reporting via QuickBooks",
            "tool_definitions": quickbooks_server.TOOL_DEFINITIONS,
            "handler": quickbooks_server.call_tool,
            "requires_env": ["QUICKBOOKS_ACCESS_TOKEN", "QUICKBOOKS_COMPANY_ID"],
        },
        # ── Cloud File Storage ────────────────────────────────────────────────
        {
            "server_id": "builtin-dropbox",
            "name": "Dropbox",
            "description": "File and folder management in Dropbox",
            "tool_definitions": dropbox_server.TOOL_DEFINITIONS,
            "handler": dropbox_server.call_tool,
            "requires_env": ["DROPBOX_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-box",
            "name": "Box",
            "description": "File management, search, and sharing via Box",
            "tool_definitions": box_server.TOOL_DEFINITIONS,
            "handler": box_server.call_tool,
            "requires_env": ["BOX_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-onedrive",
            "name": "Microsoft OneDrive",
            "description": "File management in Microsoft OneDrive via Graph API",
            "tool_definitions": microsoft_onedrive_server.TOOL_DEFINITIONS,
            "handler": microsoft_onedrive_server.call_tool,
            "requires_env": ["ONEDRIVE_ACCESS_TOKEN"],
        },
        # ── AWS ──────────────────────────────────────────────────────────────
        {
            "server_id": "builtin-aws-cloudwatch",
            "name": "AWS CloudWatch",
            "description": "AWS CloudWatch metrics, alarms, and log insights",
            "tool_definitions": aws_cloudwatch_server.TOOL_DEFINITIONS,
            "handler": aws_cloudwatch_server.call_tool,
            "requires_env": ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"],
        },
        {
            "server_id": "builtin-aws-iam",
            "name": "AWS IAM",
            "description": "AWS IAM users, roles, policies, and access management",
            "tool_definitions": aws_iam_server.TOOL_DEFINITIONS,
            "handler": aws_iam_server.call_tool,
            "requires_env": ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"],
        },
        {
            "server_id": "builtin-aws-lambda",
            "name": "AWS Lambda",
            "description": "AWS Lambda function invocation and management",
            "tool_definitions": aws_lambda_server.TOOL_DEFINITIONS,
            "handler": aws_lambda_server.call_tool,
            "requires_env": ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"],
        },
        {
            "server_id": "builtin-aws-s3",
            "name": "AWS S3",
            "description": "AWS S3 bucket and object management",
            "tool_definitions": aws_s3_server.TOOL_DEFINITIONS,
            "handler": aws_s3_server.call_tool,
            "requires_env": ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"],
        },
        # ── Azure DevOps ──────────────────────────────────────────────────────
        {
            "server_id": "builtin-azure-devops",
            "name": "Azure DevOps",
            "description": "Azure DevOps repos, pipelines, work items, and boards",
            "tool_definitions": azure_devops_server.TOOL_DEFINITIONS,
            "handler": azure_devops_server.call_tool,
            "requires_env": ["AZURE_DEVOPS_TOKEN", "AZURE_DEVOPS_ORG"],
        },
        # ── Cloud & Infrastructure ────────────────────────────────────────────
        {
            "server_id": "builtin-digitalocean",
            "name": "DigitalOcean",
            "description": "DigitalOcean droplets, Kubernetes clusters, and databases",
            "tool_definitions": digitalocean_server.TOOL_DEFINITIONS,
            "handler": digitalocean_server.call_tool,
            "requires_env": ["DIGITALOCEAN_TOKEN"],
        },
        {
            "server_id": "builtin-docker",
            "name": "Docker",
            "description": "Docker containers, images, volumes, and networks",
            "tool_definitions": docker_server.TOOL_DEFINITIONS,
            "handler": docker_server.call_tool,
            "requires_env": [],
        },
        {
            "server_id": "builtin-heroku",
            "name": "Heroku",
            "description": "Heroku apps, dynos, add-ons, and deployments",
            "tool_definitions": heroku_server.TOOL_DEFINITIONS,
            "handler": heroku_server.call_tool,
            "requires_env": ["HEROKU_API_KEY"],
        },
        {
            "server_id": "builtin-kubernetes",
            "name": "Kubernetes",
            "description": "Kubernetes pods, deployments, services, and namespaces",
            "tool_definitions": kubernetes_server.TOOL_DEFINITIONS,
            "handler": kubernetes_server.call_tool,
            "requires_env": ["KUBE_API_SERVER", "KUBE_TOKEN"],
        },
        {
            "server_id": "builtin-netlify",
            "name": "Netlify",
            "description": "Netlify sites, deploys, functions, and DNS management",
            "tool_definitions": netlify_server.TOOL_DEFINITIONS,
            "handler": netlify_server.call_tool,
            "requires_env": ["NETLIFY_ACCESS_TOKEN"],
        },
        {
            "server_id": "builtin-vercel",
            "name": "Vercel",
            "description": "Vercel deployments, projects, domains, and env vars",
            "tool_definitions": vercel_server.TOOL_DEFINITIONS,
            "handler": vercel_server.call_tool,
            "requires_env": ["VERCEL_TOKEN"],
        },
    ]

    # Deduplicate: later entries (more complete implementations) win over earlier ones.
    seen: dict[str, int] = {}
    deduplicated: list[dict] = []
    for cfg in raw_configs:
        sid = cfg["server_id"]
        if sid in seen:
            deduplicated[seen[sid]] = cfg  # overwrite with the later, better entry
        else:
            seen[sid] = len(deduplicated)
            deduplicated.append(cfg)
    return deduplicated


async def register_builtin_servers(registry: Any, tenant_ctx: Any) -> int:
    """Register all built-in MCP servers that have their required env vars set.

    Returns the number of servers successfully registered.
    """
    import logging
    import os

    from app.mcp.registry import MCPRegistry, MCPServerConfig

    count = 0
    for cfg in get_builtin_server_configs():
        # Only register if all required env vars are present and non-empty
        if all(os.getenv(env, "") for env in cfg.get("requires_env", [])):
            try:
                server_config = MCPServerConfig(
                    server_id=cfg["server_id"],
                    name=cfg["name"],
                    description=cfg.get("description", ""),
                    base_url="builtin://",
                    enabled=True,
                    tool_definitions=cfg["tool_definitions"],
                    builtin_handler=cfg["handler"],
                )
                await registry.register(server_config, tenant_ctx=tenant_ctx)
                # Also register handler in the process-local registry so it
                # survives Redis serialization round-trips (builtin_handler is
                # excluded from JSON).
                MCPRegistry.register_builtin_handler(cfg["server_id"], cfg["handler"])
                count += 1
            except Exception as exc:
                logging.getLogger(__name__).warning(
                    "builtin_server_register_failed: %s %s", cfg["name"], exc
                )
    return count
