apiVersion: v1
kind: Service
metadata:
  name: agentverse-backend
  namespace: agentverse
spec:
  selector:
    app: agentverse-backend
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
