{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentverse.secretName" . }}
  labels:
    {{- include "agentverse.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioRootUser | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioRootPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  VAULT_MASTER_KEY: {{ .Values.secrets.vaultMasterKey | quote }}
  GOAL_TOKEN_SECRET: {{ .Values.secrets.goalTokenSecret | quote }}
  MANIFEST_SIGNING_SECRET: {{ .Values.secrets.manifestSigningSecret | quote }}
  PLATFORM_ADMIN_KEY: {{ .Values.secrets.platformAdminKey | quote }}
{{- end }}
